Repository nnstreamer/nntrainer, pull requests merged in 2020-11, with the labels that each got.

#669 [Test/Refactor] Restructure data format @open sesame 10/28 14:36
  packaging/unittest_models.tar.gz
  test/input_gen/genModelTests.py
  test/input_gen/recorder.py
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2GO

#697 [tensorfilter] Bug fix of tranpose
  Applications/Tizen_native/CustomShortcut/res/model.ini
  Applications/Tizen_native/CustomShortcut/src/data.c
  Applications/TransferLearning/Draw_Classification/jni/main.cpp
  nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
  test/nnstreamer_filter_nntrainer/runTest.sh
Labels: PR/READY2GO, RELEASE CRITICAL, bug

#715 [README] Bugfix for image display
  Applications/KNN/README.md
  Applications/MNIST/README.md
  Applications/TransferLearning/Draw_Classification/README.md
Labels: RELEASE CRITICAL

#728 [AppContext] Add AppContext
  nntrainer/app_context.cpp
  nntrainer/app_context.h
  nntrainer/meson.build
  packaging/nntrainer.spec
  test/unittest/meson.build
  test/unittest/unittest_nntrainer_appcontext.cpp
Labels: PR/READY2GO

#733 [Model] Apply appcontext
  Applications/TransferLearning/Draw_Classification/jni/Android.mk
  Applications/TransferLearning/Draw_Classification/jni/main.cpp
  jni/Android.mk
  nntrainer/models/model_loader.cpp
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
Labels: PR/READY2GO

#740 [Optimizer] Add enum type factory
  api/ccapi/src/factory.cpp
  nntrainer/optimizers/optimizer_factory.cpp
  nntrainer/optimizers/optimizer_factory.h
Labels: PR/READY2GO

#745 [AppContext] Add register, invoke factory @open sesame 11/26 18:15
  nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
  nntrainer/app_context.cpp
  nntrainer/app_context.h
  test/unittest/unittest_nntrainer_appcontext.cpp
Labels: PR/READY2GO

#752 [var_grad] Add var_grad for input/output lists
  jni/Android.mk
  nntrainer/tensor/meson.build
  nntrainer/tensor/var_grad.cpp
  nntrainer/tensor/var_grad.h
  nntrainer/tensor/weight.cpp
  nntrainer/tensor/weight.h
  packaging/nntrainer.spec
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO

#754 [layers] Split backwarding into smaller functions
  nntrainer/layers/activation_layer.cpp
  nntrainer/layers/activation_layer.h
  nntrainer/layers/addition_layer.cpp
  nntrainer/layers/addition_layer.h
  nntrainer/layers/bn_layer.cpp
  nntrainer/layers/bn_layer.h
  nntrainer/layers/concat_layer.cpp
  nntrainer/layers/concat_layer.h
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/conv2d_layer.h
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/fc_layer.h
  nntrainer/layers/flatten_layer.cpp
  nntrainer/layers/flatten_layer.h
  nntrainer/layers/input_layer.cpp
  nntrainer/layers/input_layer.h
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/layers/loss_layer.cpp
  nntrainer/layers/loss_layer.h
  nntrainer/layers/nnstreamer_layer.cpp
  nntrainer/layers/nnstreamer_layer.h
  nntrainer/layers/output_layer.cpp
  nntrainer/layers/output_layer.h
  nntrainer/layers/pooling2d_layer.cpp
  nntrainer/layers/pooling2d_layer.h
  nntrainer/layers/tflite_layer.cpp
  nntrainer/layers/tflite_layer.h
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2GO

#759 [Deps] Remove openmp dependency
  Applications/KNN/jni/Android.mk
  Applications/LogisticRegression/jni/Android.mk
  Applications/MNIST/jni/Android.mk
  Applications/ReinforcementLearning/DeepQ/jni/Android.mk
  Applications/TransferLearning/CIFAR_Classification/jni/Android.mk
  Applications/TransferLearning/Draw_Classification/jni/Android.mk
  Applications/VGG/jni/Android.mk
  Applications/utils/jni/Android.mk
  jni/Android.mk
  meson.build
  nntrainer/meson.build
Labels: PR/READY2GO

#746 [AppContext][Optimizer] Register Default ops at the beginning @open sesame 11/27 15:35
  api/ccapi/include/optimizer.h
  api/ccapi/src/factory.cpp
  nntrainer/app_context.cpp
  nntrainer/app_context.h
  nntrainer/optimizers/adam.h
  nntrainer/optimizers/sgd.h
Labels: PR/READY2GO

#755 [graph] Skip backwarding for non-trainable layers
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/layer_internal.h
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2GO

#776 [ModelLoader] Use vector when creating layer
  nntrainer/layers/layer.cpp
  nntrainer/models/model_loader.cpp
  nntrainer/models/model_loader.h
  nntrainer/models/neuralnet.cpp
  test/unittest/unittest_nntrainer_internal.cpp
Labels: PR/READY2GO

#768 [ Graph ] remove grad mem buffer for backwarding
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/activation_layer.cpp
  nntrainer/layers/activation_layer.h
  nntrainer/layers/addition_layer.cpp
  nntrainer/layers/bn_layer.cpp
  nntrainer/layers/concat_layer.cpp
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/flatten_layer.cpp
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/layers/loss_layer.cpp
  nntrainer/layers/output_layer.cpp
  nntrainer/layers/pooling2d_layer.cpp
  nntrainer/models/neuralnet.cpp
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO

#760 [Custom] Add an example scaffolding
  Applications/Custom/LayerClient/README.md
  Applications/Custom/LayerClient/jni/Android.mk
  Applications/Custom/LayerClient/jni/Application.mk
  Applications/Custom/LayerClient/jni/main.cpp
  Applications/Custom/LayerClient/jni/meson.build
  Applications/Custom/LayerClient/jni/pow.cpp
  Applications/Custom/LayerClient/jni/pow.h
  Applications/Custom/LayerClient/res/custom_layer_client.ini
  Applications/Custom/README.md
  Applications/meson.build
Labels: PR/READY2GO
