Repository nnstreamer/nntrainer, pull requests merged in 2020-09, with the labels that each got.

#497 [tensor] bug fix for the sum
  nntrainer/src/tensor.cpp
Labels: bug

#494 [ UNITTEST ] Integer Unit test for conv2d
  packaging/unittest_layers.tar.gz
  test/input_gen/genInput.py
  test/unittest/unittest_nntrainer_layers.cpp
Labels: RELEASE CRITICAL

#503 [ TOKEN ] Update weight decay to weight regularizer
  Applications/Tizen_CAPI/capi_file.c
  Applications/Tizen_CAPI/capi_func.c
  README.md
  api/capi/include/nntrainer.h
  docs/configuration-ini.md
  nntrainer/include/layer.h
  nntrainer/include/optimizer.h
  nntrainer/include/parse_util.h
  nntrainer/src/conv2d_layer.cpp
  nntrainer/src/fc_layer.cpp
  nntrainer/src/layer.cpp
  nntrainer/src/parse_util.cpp
  test/include/nntrainer_test_util.h
  test/tizen_capi/unittest_tizen_capi.cpp
  test/tizen_capi/unittest_tizen_capi_layer.cpp
  test/unittest/unittest_nntrainer_layers.cpp
Labels: RELEASE CRITICAL

#496 [dataset] check bufsize at init
  nntrainer/include/databuffer.h
  nntrainer/src/databuffer.cpp
  nntrainer/src/databuffer_file.cpp
  nntrainer/src/databuffer_func.cpp
  nntrainer/src/model_loader.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: RELEASE CRITICAL

#502 [CAPI] Fix potential issue in capi
  api/capi/src/nntrainer.cpp
  nntrainer/include/layer.h
Labels: RELEASE CRITICAL

#491 [ UTIL ] Add BLAS Interface
  jni/Android.mk
  nntrainer/include/blas_interface.h
  nntrainer/include/tensor.h
  nntrainer/meson.build
  nntrainer/src/activation_layer.cpp
  nntrainer/src/blas_interface.cpp
  nntrainer/src/conv2d_layer.cpp
  nntrainer/src/tensor.cpp
  packaging/nntrainer.spec
  test/unittest/unittest_nntrainer_layers.cpp
Labels: RELEASE CRITICAL

#516 [ SVACE ] Using rand_r instead of rand
  Applications/Classification/jni/main.cpp
  Applications/Tizen_CAPI/capi_func.c
  api/capi/src/nntrainer.cpp
Labels: RELEASE CRITICAL

#519 [Docs] Fix typo on classificaion
  Applications/Classification/README.md
Labels: TRIVIAL, documentation

#518 Fix normalization for specific case
  nntrainer/src/tensor.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: RELEASE CRITICAL

#521 [ SVACE ] Fix minor issues reported by svace
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
  api/capi/src/nntrainer.cpp
  nntrainer/include/model_loader.h
  test/tizen_capi/unittest_tizen_capi.cpp
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
Labels: RELEASE CRITICAL

#522 [ Coverity ] Fix Race Condition issue about databuffer
  nntrainer/src/databuffer.cpp
  nntrainer/src/databuffer_file.cpp
  nntrainer/src/databuffer_func.cpp
Labels: RELEASE CRITICAL

#523 [ DataBuffer ] Hot fix for data buffer
  nntrainer/src/databuffer.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: RELEASE CRITICAL

#525 [ DataBuffer ] Fix for conner cases.
  nntrainer/src/databuffer.cpp
  nntrainer/src/databuffer_file.cpp
Labels: RELEASE CRITICAL

#524 [ Example ] Add Inference Mode & Example
  nntrainer/include/neuralnet.h
  nntrainer/src/model_loader.cpp
  nntrainer/src/neuralnet.cpp
Labels: RELEASE CRITICAL

#533 [dataset] Support setting user_data for generator dataset
  api/capi/src/nntrainer.cpp
  nntrainer/include/databuffer.h
  nntrainer/src/databuffer.cpp
  nntrainer/src/databuffer_func.cpp
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
Labels: RELEASE CRITICAL

#547 [ Bug ] Free content of g_file_get_contents
  nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
Labels: RELEASE CRITICAL

#538 Add gitignore for python generated files
  .gitignore
Labels: TRIVIAL

#512 Update bn layer forwarding @open sesame 09/15 21:11
  nntrainer/include/bn_layer.h
  nntrainer/src/bn_layer.cpp
  nntrainer/src/tensor_dim.cpp
  packaging/unittest_layers.tar.gz
  test/input_gen/genInput.py
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO

#552 [meson] Move dependencies to correct location
  Applications/TransferLearning/Draw_Classification/jni/meson.build
  nnstreamer/tensor_filter/meson.build
Labels: TRIVIAL

#554 [ LICENSE ] Fix license header
  nntrainer/include/nntrainer_error.h
Labels: RELEASE CRITICAL

#564 [TensorDim] Fix index checks
  nntrainer/src/tensor_dim.cpp
Labels: RELEASE CRITICAL

#560 [Tensor] Fix bug in the broadcast support @open sesame 09/18 11:48
  nntrainer/src/tensor.cpp
  test/include/nntrainer_test_util.h
  test/nntrainer_test_util.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2GO, bug

#568 [Docs] Update example link
  README.md
Labels: TRIVIAL, documentation

#576 [CS] Remove leading underscore
  Applications/Tizen_native/CustomShortcut/src/data.c
  Applications/Tizen_native/CustomShortcut/src/view.c
Labels: TRIVIAL

#570 [CustomShortcut] Update docs and model @open sesame 09/22 14:05
  Applications/Tizen_native/CustomShortcut/README.md
  Applications/Tizen_native/CustomShortcut/res/model.ini
Labels: TRIVIAL

#581 [layers] Move constructors must be noexcept
  nntrainer/include/addition_layer.h
  nntrainer/include/bn_layer.h
  nntrainer/include/conv2d_layer.h
  nntrainer/include/fc_layer.h
  nntrainer/include/flatten_layer.h
  nntrainer/include/input_layer.h
  nntrainer/include/optimizer.h
  nntrainer/include/pooling2d_layer.h
Labels: TRIVIAL

#588 [inference] Inference bug fix @open sesame 09/23 15:03
  nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
  nntrainer/src/loss_layer.cpp
  nntrainer/src/neuralnet.cpp
Labels: RELEASE CRITICAL, bug

#591 [dist/tizen] Package tensor filter properly
  packaging/nntrainer.spec
Labels: RELEASE CRITICAL, bug

#580 [CS] Add inference page @open sesame 09/24 19:32
  Applications/Tizen_native/CustomShortcut/inc/data.h
  Applications/Tizen_native/CustomShortcut/inc/main.h
  Applications/Tizen_native/CustomShortcut/inc/view.h
  Applications/Tizen_native/CustomShortcut/res/edje/main.edc
  Applications/Tizen_native/CustomShortcut/src/data.c
  Applications/Tizen_native/CustomShortcut/src/main.c
  Applications/Tizen_native/CustomShortcut/src/view.c
Labels: migrate to main

#603 [model] Merge model finalize to destructor
  Applications/LogisticRegression/jni/main.cpp
  Applications/MNIST/jni/main.cpp
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
  Applications/TransferLearning/CIFAR_Classification/jni/main.cpp
  Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp
  api/capi/src/nntrainer.cpp
  nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
  nntrainer/include/neuralnet.h
  nntrainer/src/neuralnet.cpp
Labels: PR/READY2GO

#593 [gitignore] Update for android build
  .gitignore
Labels: TRIVIAL
