Repository nnstreamer/nntrainer, pull requests merged in 2020-07, with the labels that each got.

#255 [layers] Add trainable feature
  nntrainer/include/layer.h
  nntrainer/src/conv2d_layer.cpp
  nntrainer/src/fc_layer.cpp
Labels: PR/READY2GO

#277 Format everyfile @open sesame 07/08 13:55
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
  Applications/Tizen_CAPI/capi_file.c
  Applications/Tizen_CAPI/capi_func.c
  Applications/Tizen_CAPI/main.c
  Applications/Tizen_native/CustomShortcut/src/main.c
  Applications/Tizen_native/CustomShortcut/src/view.c
  api/capi/include/nntrainer.h
  api/capi/src/nntrainer.cpp
  nntrainer/include/conv2d_layer.h
  nntrainer/include/input_layer.h
  nntrainer/include/layer.h
  nntrainer/include/optimizer.h
  nntrainer/include/parse_util.h
  nntrainer/include/tensor.h
  nntrainer/src/conv2d_layer.cpp
  nntrainer/src/layer.cpp
  nntrainer/src/neuralnet.cpp
  nntrainer/src/optimizer.cpp
  nntrainer/src/parse_util.cpp
  nntrainer/src/tensor.cpp
  test/include/nntrainer_test_util.h
  test/unittest/unittest_nntrainer_lazy_tensor.cpp
Labels: PR/READY2GO

#258 [bug fixes] [tensor] Tensor constructor should not set zero
  nntrainer/include/tensor.h
  nntrainer/src/conv2d_layer.cpp
  nntrainer/src/pooling2d_layer.cpp
  nntrainer/src/tensor.cpp
  nntrainer/src/util_func.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2GO, bug

#279 [API] Update C-API semantics
  Applications/Tizen_CAPI/capi_file.c
  Applications/Tizen_CAPI/capi_func.c
  api/capi/include/nntrainer.h
  api/capi/include/nntrainer_internal.h
  api/capi/src/nntrainer.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: RELEASE CRITICAL

#261 [API] Search layer by name in C-API
  Applications/Classification/res/Classification_new.ini
  api/capi/include/nntrainer.h
  api/capi/include/nntrainer_internal.h
  api/capi/src/nntrainer.cpp
  nntrainer/include/layer.h
  nntrainer/include/neuralnet.h
  nntrainer/src/layer.cpp
  nntrainer/src/neuralnet.cpp
  nntrainer/src/parse_util.cpp
  test/tizen_capi/test_conf.ini
  test/tizen_capi/unittest_tizen_capi.cpp
  test/unittest/unittest_nntrainer_layers.cpp
Labels: RELEASE CRITICAL

#297 [API] Bug fix in C-API get_layer
  api/capi/src/nntrainer.cpp
Labels: bug

#304 [Urgent][Fix/Coverage] Fix the coverage generator to use python3
  test/unittestcoverage.py
Labels: BUILD/CI, PR/READY2GO

#306 [data buffer] Bug fix for data buffer
  nntrainer/include/databuffer.h
  nntrainer/include/databuffer_file.h
  nntrainer/include/databuffer_func.h
  nntrainer/src/databuffer.cpp
  nntrainer/src/databuffer_file.cpp
  nntrainer/src/databuffer_func.cpp
Labels: bug

#296 [API] Update API namespace and use enum for opitmizer
  Applications/Tizen_CAPI/capi_file.c
  Applications/Tizen_CAPI/capi_func.c
  Applications/Tizen_CAPI/main.c
  api/capi/include/nntrainer.h
  api/capi/include/nntrainer_internal.h
  api/capi/include/nntrainer_util.h
  api/capi/meson.build
  api/capi/src/nntrainer.cpp
  api/capi/src/nntrainer_util.cpp
  nntrainer/include/neuralnet.h
  nntrainer/src/neuralnet.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
  test/tizen_capi/unittest_tizen_capi_layer.cpp
  test/tizen_capi/unittest_tizen_capi_optimizer.cpp
Labels: RELEASE CRITICAL

#284 [CAPI] Add ml_nnmodel_get_summary
  api/capi/include/nntrainer.h
Labels: RELEASE CRITICAL

#312 [CAPI] Added more unittests for tizen capi
  nntrainer/src/databuffer_func.cpp
  test/tizen_capi/meson.build
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
Labels: RELEASE CRITICAL

#313 [CAPI] Add functions to be supported later
  api/capi/include/nntrainer_internal.h
Labels: PR/READY2GO, RELEASE CRITICAL

#283 [API] Finalize the first draft of C-API
  api/capi/doc/nntrainer_doc.h
  api/capi/include/nntrainer.h
  api/capi/include/nntrainer_internal.h
Labels: PR/READY2GO

#322 [api] remove duplicate declaration
  api/capi/include/nntrainer_internal.h
Labels: bug

#329 [c-api] Function namespace correction
  api/capi/include/nntrainer.h
Labels: RELEASE CRITICAL

#328 [api] remove duplicate declarations
  Applications/mnist/jni/nntrainer_mnist
  api/capi/include/nntrainer.h
Labels: RELEASE CRITICAL

#335 [unittest] Add unittest for backwarding of loss layers
  nntrainer/src/activation_layer.cpp
  nntrainer/src/loss_layer.cpp
  nntrainer/src/util_func.cpp
  packaging/unittest_layers.tar.gz
  test/input_gen/genInput.py
  test/unittest/unittest_nntrainer_layers.cpp
Labels: bug

#373 KNN notation change
  README.md
Labels: sos-masters
