Repository nnstreamer/nntrainer, pull requests merged in 2020-12, with the labels that each got.

#783 [Chores] CustomShortcut bug
  Applications/Tizen_native/CustomShortcut/res/model.ini
Labels: bug

#796 [meson.build] Change join_paths to / in meson.build files
  Applications/KNN/jni/meson.build
  Applications/LogisticRegression/jni/meson.build
  Applications/ReinforcementLearning/DeepQ/jni/meson.build
  Applications/TransferLearning/CIFAR_Classification/jni/meson.build
  Applications/TransferLearning/Draw_Classification/jni/meson.build
  Applications/VGG/jni/meson.build
  api/capi/meson.build
  api/ccapi/meson.build
  meson.build
  nnstreamer/tensor_filter/meson.build
  nntrainer/dataset/meson.build
  nntrainer/graph/meson.build
  nntrainer/layers/meson.build
  nntrainer/meson.build
  nntrainer/models/meson.build
  nntrainer/optimizers/meson.build
  nntrainer/tensor/meson.build
  nntrainer/utils/meson.build
  test/unittest/meson.build
Labels: PR/READY2MERGE

#800 [Optim] Add shortcut to dot product @open sesame 12/14 22:55
  nntrainer/tensor/blas_interface.cpp
  nntrainer/tensor/blas_interface.h
  nntrainer/tensor/tensor.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#817 [tensor] Set stride for shared tensor
  nntrainer/tensor/tensor.cpp
Labels: bug

#818 [Profiler] Change profiler specs
  nntrainer/utils/profiler.cpp
  nntrainer/utils/profiler.h
  test/unittest/unittest_nntrainer_profiler.cpp
Labels: PR/READY2MERGE

#812 [layer] Move layer input/output management to manager
  Applications/Custom/LayerClient/jni/pow.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/activation_layer.cpp
  nntrainer/layers/addition_layer.cpp
  nntrainer/layers/bn_layer.cpp
  nntrainer/layers/concat_layer.cpp
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/flatten_layer.cpp
  nntrainer/layers/input_layer.cpp
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/layers/loss_layer.cpp
  nntrainer/layers/nnstreamer_layer.cpp
  nntrainer/layers/output_layer.cpp
  nntrainer/layers/pooling2d_layer.cpp
  nntrainer/layers/tflite_layer.cpp
  nntrainer/models/neuralnet.cpp
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
  nntrainer/tensor/var_grad.h
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2MERGE, rebase required

#835 [Fix] Assign default value for max_deriv size @open sesame 12/29 15:57
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
Labels: PR/READY2GO, bug
