Repository nnstreamer/nntrainer, pull requests merged in 2020-08, with the labels that each got.

#363 [C-API] C-API updated with tizen ACR
  Applications/Classification/jni/main_func.cpp
  Applications/Tizen_CAPI/capi_func.c
  Applications/mnist/jni/main.cpp
  api/capi/doc/nntrainer_doc.h
  api/capi/include/nntrainer.h
  api/nntrainer-api-common.h
  nntrainer/src/databuffer_func.cpp
  test/include/nntrainer_test_util.h
  test/input_gen/genInput.py
  test/nntrainer_test_util.cpp
Labels: PR/READY2GO

#407 [Tensor] Enable default copy constructor @open sesame 08/10 14:32
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
  nntrainer/include/activation_layer.h
  nntrainer/include/bn_layer.h
  nntrainer/include/conv2d_layer.h
  nntrainer/include/fc_layer.h
  nntrainer/include/flatten_layer.h
  nntrainer/include/input_layer.h
  nntrainer/include/layer.h
  nntrainer/include/lazy_tensor.h
  nntrainer/include/loss_layer.h
  nntrainer/include/neuralnet.h
  nntrainer/include/optimizer.h
  nntrainer/include/pooling2d_layer.h
  nntrainer/include/tensor.h
  nntrainer/src/activation_layer.cpp
  nntrainer/src/bn_layer.cpp
  nntrainer/src/conv2d_layer.cpp
  nntrainer/src/fc_layer.cpp
  nntrainer/src/flatten_layer.cpp
  nntrainer/src/input_layer.cpp
  nntrainer/src/loss_layer.cpp
  nntrainer/src/neuralnet.cpp
  nntrainer/src/pooling2d_layer.cpp
  nntrainer/src/tensor.cpp
  test/unittest/unittest_nntrainer_layers.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2GO

#421 [capi] Add tizen feature checking
  api/capi/include/nntrainer.h
  api/capi/include/nntrainer_internal.h
  api/capi/meson.build
  api/capi/src/nntrainer-capi-tizen-feature-check.cpp
  api/capi/src/nntrainer.cpp
  meson.build
  meson_options.txt
  packaging/nntrainer.spec
  test/tizen_capi/unittest_tizen_capi.cpp
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
  test/tizen_capi/unittest_tizen_capi_layer.cpp
  test/tizen_capi/unittest_tizen_capi_optimizer.cpp
Labels: RELEASE CRITICAL

#430 [softmax] Bug fix for softmax
  nntrainer/include/tensor.h
  nntrainer/src/activation_layer.cpp
Labels: bug

#431 [CAPI] Add comments for tizen privileges
  api/capi/include/nntrainer.h
Labels: PR/READY2GO, RELEASE CRITICAL

#440 [capi] Comply with Tizen ACR comments
  api/capi/doc/nntrainer_doc.h
  api/capi/include/nntrainer.h
  api/capi/include/nntrainer_internal.h
  api/capi/src/nntrainer.cpp
  api/nntrainer-api-common.h
  nntrainer/include/nntrainer_error.h
Labels: RELEASE CRITICAL

#411 [config] Separate loading model with config from neuralnetwork class
  Applications/Classification/jni/main.cpp
  Applications/Classification/jni/main_func.cpp
  Applications/LogisticRegression/jni/main.cpp
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
  Applications/Training/jni/main.cpp
  Applications/mnist/jni/main.cpp
  api/capi/src/nntrainer.cpp
  jni/Android.mk
  nntrainer/include/loss_layer.h
  nntrainer/include/model_loader.h
  nntrainer/include/neuralnet.h
  nntrainer/include/util_func.h
  nntrainer/meson.build
  nntrainer/src/model_loader.cpp
  nntrainer/src/neuralnet.cpp
  nntrainer/src/util_func.cpp
  packaging/nntrainer.spec
  test/include/nntrainer_test_util.h
  test/unittest/unittest_nntrainer_internal.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2GO

#486 [tizen/dist] Update tizen packaging
  packaging/nntrainer.spec
Labels: RELEASE CRITICAL

#402 [Layer] Add support for element-wise add layer
  Applications/mnist/Tensorflow/Training_Keras.py.pk
  Applications/mnist/Tensorflow/__pycache__/dataset.cpython-35.pyc
  Applications/mnist/Tensorflow/mnist_trainingSet.dat
  jni/Android.mk
  nntrainer/include/addition_layer.h
  nntrainer/include/layer.h
  nntrainer/meson.build
  nntrainer/src/addition_layer.cpp
  nntrainer/src/parse_util.cpp
  packaging/nntrainer.spec
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO
