Repository nnstreamer/nntrainer, pull requests merged in 2020-10, with the labels that each got.

#607 [CS] Enlarge fonts and s/test/eval
  Applications/Tizen_native/CustomShortcut/res/edje/main.edc
  Applications/Tizen_native/CustomShortcut/src/data.c
  Applications/Tizen_native/CustomShortcut/src/main.c
Labels: PR/READY2GO

#616 [ Packaging ] Meta Package for NNTrainer
  packaging/nntrainer.spec
Labels: RELEASE CRITICAL

#623 [Databuffer] Fix queue is not emptied properly
  nntrainer/src/databuffer.cpp
Labels: RELEASE CRITICAL

#628 [CS] Add color to the label and fix status
  Applications/Tizen_native/CustomShortcut/src/data.c
  Applications/Tizen_native/CustomShortcut/src/view.c
Labels: TRIVIAL
