Repository nnstreamer/nntrainer, pull requests merged in 2020-06, with the labels that each got.

#157 [loss] Added missing weight decay loss
  nntrainer/src/fc_layer.cpp
  nntrainer/src/neuralnet.cpp
Labels: bug

#161 [error] error macros not defined
  nntrainer/include/nntrainer_error.h
Labels: bug

#190 Add test for activation layer
  test/include/nntrainer_test_util.h
  test/nntrainer_test_util.cpp
  test/unittest/unittest_nntrainer_layers.cpp
  test/unittest/unittest_nntrainer_lazy_tensor.cpp
Labels: PR/READY2GO

#222 [fc_layer] Add the deleted statement
  nntrainer/src/fc_layer.cpp
Labels: PR/READY2GO, bug

#219 [bias] Bias updation missing for sgd
  nntrainer/include/optimizer.h
  nntrainer/src/optimizer.cpp
Labels: bug

#225 Fix optimizer signature
  nntrainer/src/fc_layer.cpp
Labels: bug

#223 [activation] Derivative for activation
  nntrainer/src/activation_layer.cpp
Labels: bug

#227 [ Conv2D ] fix calculate parameter of optimizer
  nntrainer/src/conv2d_layer.cpp
Labels: bug

#224 [optimizer] Optimizer to manage list of weights @open sesame 06/25 13:00
  nntrainer/include/conv2d_layer.h
  nntrainer/include/optimizer.h
  nntrainer/src/conv2d_layer.cpp
  nntrainer/src/fc_layer.cpp
  nntrainer/src/optimizer.cpp
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO

#242 [optimizer] Bug fix
  nntrainer/src/optimizer.cpp
Labels: PR/READY2GO, bug

#228 [unittest] generate fc unittests @open sesame 06/30 15:31
  .gitignore
  nntrainer/src/fc_layer.cpp
  nntrainer/src/tensor.cpp
  nntrainer/src/util_func.cpp
  packaging/unittest_layers.tar.gz
  test/input_gen/genInput.py
  test/unittest/meson.build
  test/unittest/unittest_nntrainer_layers.cpp
  test/unittest/unittest_util_func.cpp
Labels: PR/READY2GO
