Repository nnstreamer/nntrainer, pull requests merged in 2021-08, with the labels that each got.

#1396 [dataset] Add file producer
  jni/Android.mk
  nntrainer/dataset/data_producers.h
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/func_data_producer.cpp
  nntrainer/dataset/func_data_producer.h
  nntrainer/dataset/meson.build
  nntrainer/dataset/random_data_producers.cpp
  nntrainer/dataset/random_data_producers.h
  nntrainer/dataset/raw_file_data_producer.cpp
  nntrainer/dataset/raw_file_data_producer.h
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  test/unittest/datasets/data_producer_common_tests.cpp
  test/unittest/datasets/meson.build
  test/unittest/datasets/unittest_func_data_producer.cpp
  test/unittest/datasets/unittest_raw_file_data_producer.cpp
Labels: PR/READY2MERGE

#1443 [ccapi] Add ccapi for model inference
  api/ccapi/include/model.h
  nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
  nnstreamer/tensor_filter/tensor_filter_nntrainer.hh
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
Labels: PR/READY2MERGE

#1439 [CAPI] Move save/load api to public
  api/capi/include/nntrainer-tizen-internal.h
  api/capi/include/nntrainer.h
Labels: RELEASE CRITICAL

#1459 [test] capi unittest fix
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: PR/READY2MERGE

#1405 [Dataset] Add thread safe queue for the buffer
  jni/Android.mk
  nntrainer/dataset/batch_queue.cpp
  nntrainer/dataset/batch_queue.h
  nntrainer/dataset/meson.build
  test/unittest/datasets/meson.build
  test/unittest/datasets/unittest_batch_queue.cpp
Labels: PR/READY2MERGE

#1407 [Dataset] Implement data getter
  nntrainer/dataset/data_producers.h
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/random_data_producers.cpp
  nntrainer/dataset/random_data_producers.h
  nntrainer/dataset/raw_file_data_producer.cpp
  nntrainer/dataset/raw_file_data_producer.h
  test/unittest/datasets/meson.build
  test/unittest/datasets/unittest_databuffer.cpp
  test/unittest/datasets/unittest_random_data_producers.cpp
Labels: PR/READY2MERGE

#1409 [Dataset] Change factory signature
  api/ccapi/include/dataset.h
  api/ccapi/src/factory.cpp
  nntrainer/dataset/databuffer_factory.cpp
  nntrainer/dataset/databuffer_file.h
  nntrainer/dataset/databuffer_func.h
  nntrainer/models/model_loader.cpp
  test/ccapi/unittest_ccapi.cpp
Labels: PR/READY2GO

#1416 [Dataset] Adopt new datagetter to databuffer
  Applications/ProductRatings/jni/main.cpp
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/databuffer_factory.cpp
  nntrainer/dataset/raw_file_data_producer.cpp
  nntrainer/dataset/raw_file_data_producer.h
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/models/neuralnet.cpp
  nntrainer/utils/base_properties.h
  test/ccapi/unittest_ccapi.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: PR/READY2GO

#1481 [fixes] Add bug fixes found with address sanitizer
  nntrainer/layers/nnstreamer_layer.cpp
  nntrainer/layers/nnstreamer_layer.h
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: bug, PR/READY2GO

#1483 [fixes] Add bug fixes from asan
  Applications/TransferLearning/Draw_Classification/jni/main.cpp
  meson.build
  nntrainer/app_context.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
Labels: bug, PR/READY2GO

#1463 [graph/neuralnet] Move manager from neuralnet to netgraph
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
Labels: PR/READY2GO

#1491 [CAPI] Reflect privilege reviews
  api/capi/include/nntrainer.h
Labels: RELEASE CRITICAL, PR/READY2MERGE

#1420 [Dataset] Add user_data set Property handler
  api/capi/src/nntrainer.cpp
  api/ccapi/include/dataset.h
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/func_data_producer.cpp
  nntrainer/dataset/func_data_producer.h
  nntrainer/utils/base_properties.h
  test/unittest/unittest_base_properties.cpp
Labels: PR/READY2MERGE

#1503 [Trivial] layer client test was not running
  Applications/Custom/LayerClient/jni/meson.build
Labels: PR/READY2MERGE

#1470 [Dataset] Implement samplewise producer for random
  nntrainer/dataset/random_data_producers.cpp
  nntrainer/dataset/random_data_producers.h
  test/unittest/datasets/data_producer_common_tests.cpp
  test/unittest/datasets/data_producer_common_tests.h
  test/unittest/datasets/unittest_random_data_producers.cpp
Labels: PR/READY2MERGE

#1498 [Backbone/CAPI] Implement backbone layer creation
  Applications/SimpleShot/task_runner.cpp
  api/ccapi/include/layer.h
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/layers/nnstreamer_layer.cpp
  nntrainer/layers/nnstreamer_layer.h
  nntrainer/layers/tflite_layer.cpp
  nntrainer/layers/tflite_layer.h
Labels: RELEASE CRITICAL

#1504 [CAPI] Reflect feature review
  api/capi/include/nntrainer.h
Labels: PR/READY2GO, RELEASE CRITICAL

#1506 [CAPI] Update description of ml_train_datagen_cb
  api/nntrainer-api-common.h
Labels: PR/READY2MERGE

#1472 [Dataset] Implement samplewise for file
  nntrainer/dataset/random_data_producers.cpp
  nntrainer/dataset/raw_file_data_producer.cpp
  nntrainer/dataset/raw_file_data_producer.h
  test/unittest/datasets/unittest_raw_file_data_producer.cpp
Labels: PR/READY2GO

#1475 [memory] Introduce memory pool and planner
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
  nntrainer/tensor/memory_planner.h
  nntrainer/tensor/memory_pool.h
Labels: PR/READY2GO

#1499 [CAPI] Open centroid KNN
  Applications/SimpleShot/meson.build
  Applications/SimpleShot/task_runner.cpp
  Applications/SimpleShot/test/simpleshot_layer_common_tests.cpp
  api/ccapi/include/layer.h
  jni/Android.mk
  nntrainer/app_context.cpp
  nntrainer/layers/centroid_knn.cpp
  nntrainer/layers/centroid_knn.h
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/meson.build
Labels: PR/READY2GO

#1514 [unittest] backbone property name update
  test/unittest/layers/unittest_layers_nnstreamer.cpp
  test/unittest/layers/unittest_layers_tflite.cpp
Labels: bug, PR/READY2GO

#1473 [Dataset] Rework func dataset to samplewise
  nntrainer/dataset/func_data_producer.cpp
  nntrainer/dataset/func_data_producer.h
  nntrainer/layers/split_layer.cpp
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  test/unittest/datasets/data_producer_common_tests.cpp
  test/unittest/datasets/unittest_func_data_producer.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2GO

#1476 [Dataset] Change finalize signature
  nntrainer/dataset/data_producers.h
  nntrainer/dataset/func_data_producer.cpp
  nntrainer/dataset/func_data_producer.h
  nntrainer/dataset/random_data_producers.cpp
  nntrainer/dataset/random_data_producers.h
  nntrainer/dataset/raw_file_data_producer.cpp
  nntrainer/dataset/raw_file_data_producer.h
Labels: PR/READY2MERGE
