Repository nnstreamer/nntrainer, pull requests merged in 2021-01, with the labels that each got.

#840 [manager] Optimize input/output memory for inference
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/addition_layer.cpp
  nntrainer/layers/concat_layer.cpp
  nntrainer/layers/loss_layer.cpp
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
  test/unittest/unittest_nntrainer_layers.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#845 [ini] add trainable property for layer
  api/ccapi/include/layer.h
  nntrainer/layers/activation_layer.h
  nntrainer/layers/flatten_layer.h
  nntrainer/layers/layer.cpp
  nntrainer/utils/parse_util.cpp
Labels: PR/READY2MERGE

#848 [Layer] Add eval mode for the training
  Applications/Custom/LayerClient/jni/pow.cpp
  Applications/Custom/LayerClient/jni/pow.h
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/activation_layer.cpp
  nntrainer/layers/activation_layer.h
  nntrainer/layers/addition_layer.cpp
  nntrainer/layers/addition_layer.h
  nntrainer/layers/bn_layer.cpp
  nntrainer/layers/bn_layer.h
  nntrainer/layers/concat_layer.cpp
  nntrainer/layers/concat_layer.h
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/conv2d_layer.h
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/fc_layer.h
  nntrainer/layers/flatten_layer.cpp
  nntrainer/layers/flatten_layer.h
  nntrainer/layers/input_layer.cpp
  nntrainer/layers/input_layer.h
  nntrainer/layers/layer_internal.h
  nntrainer/layers/loss_layer.cpp
  nntrainer/layers/loss_layer.h
  nntrainer/layers/nnstreamer_layer.cpp
  nntrainer/layers/nnstreamer_layer.h
  nntrainer/layers/output_layer.cpp
  nntrainer/layers/output_layer.h
  nntrainer/layers/pooling2d_layer.cpp
  nntrainer/layers/pooling2d_layer.h
  nntrainer/layers/tflite_layer.cpp
  nntrainer/layers/tflite_layer.h
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
Labels: PR/READY2MERGE

#872 [optimization] Bug fix for in-place layer optimization
  nntrainer/graph/network_graph.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: RELEASE CRITICAL, bug

#884 [Fix] Reflect changes to upstream/main
  nntrainer/layers/preprocess_flip_layer.cpp
  nntrainer/layers/preprocess_flip_layer.h
  nntrainer/layers/preprocess_translate_layer.cpp
  nntrainer/layers/preprocess_translate_layer.h
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO
