Repository nnstreamer/nntrainer, pull requests merged in 2021-11, with the labels that each got.

#1694 [tp] Implement reidentifySource()
  nntrainer/tensor/tensor_pool.cpp
Labels: PR/READY2GO

#1701 [Test] Add ml singleshot example
  test/meson.build
  test/nnstreamer/meson.build
  test/nnstreamer/test_nnstreamer_single.cpp
Labels: PR/READY2GO, RELEASE CRITICAL

#1697 [Tp] Rename requestTensor -> request
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/tensor_pool.cpp
  nntrainer/tensor/tensor_pool.h
  test/unittest/unittest_nntrainer_tensor_pool.cpp
Labels: PR/READY2MERGE, PR/OK2GO

#1715 [Fix] api feature check problem
  api/capi/include/nntrainer_internal.h
  api/capi/src/nntrainer-capi-tizen-feature-check.cpp
  test/nnstreamer/meson.build
  test/nnstreamer/test_nnstreamer_single.cpp
Labels: PR/READY2MERGE

#1718 [Build] Fix fbs causing rebuilding
  nntrainer/compiler/meson.build
Labels: TRIVIAL

#1730 [Feature check] Add tizen 6.5 compatibility
  api/capi/src/nntrainer-capi-tizen-feature-check.cpp
  meson.build
  meson_options.txt
  packaging/nntrainer.spec
Labels: PR/READY2GO

#1712 [Trivial] Delete duplicated file @open sesame 11/19 10:09
  test/unittest/layers/unitest_layer_node.cpp
Labels: PR/OK2GO

#1692 [tensor] Add checks for non-contiguous tensor before operations @open sesame 11/19 23:17
  nntrainer/tensor/tensor.cpp
Labels: PR/READY2MERGE

#1745 [ Android ] add static option for openmp
  jni/Android.mk.in
Labels: PR/OK2GO
