Repository nnstreamer/nntrainer, pull requests merged in 2021-12, with the labels that each got.

#1749 [KLD loss] kld loss scaffolding
  jni/Android.mk
  nntrainer/layers/loss/kld_loss_layer.cpp
  nntrainer/layers/loss/kld_loss_layer.h
  nntrainer/layers/loss/meson.build
Labels: TRIVIAL

#1733 [trivial] Add note on the freq
  nntrainer/compiler/multiout_realizer.cpp
Labels: TRIVIAL, PR/READY2MERGE

#1735 [Test] Add simple multiple inout case
  test/unittest/models/meson.build
  test/unittest/models/models_golden_test.cpp
  test/unittest/models/models_golden_test.h
  test/unittest/models/unittest_models_multiout.cpp
Labels: PR/READY2MERGE

#1757 [Tensor Sharing] Make tensor sharing private by default
  nntrainer/layers/grucell.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/lstm.cpp
  nntrainer/layers/lstmcell.cpp
  nntrainer/layers/rnncell.cpp
Labels: PR/READY2MERGE

#1752 [Fix] Setting batch after finalize/initialize
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/bn_layer.cpp
  nntrainer/layers/grucell.cpp
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/lstmcell.cpp
  nntrainer/layers/rnncell.cpp
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2GO, rebase required

#1774 [layer] bug fix for array initializer
  nntrainer/layers/attention_layer.cpp
  nntrainer/layers/bn_layer.cpp
  nntrainer/layers/centroid_knn.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/conv1d_layer.cpp
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/embedding.cpp
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/fc_layer.h
  nntrainer/layers/gru.cpp
  nntrainer/layers/grucell.cpp
  nntrainer/layers/lstm.cpp
  nntrainer/layers/lstmcell.cpp
  nntrainer/layers/lstmcell_core.cpp
  nntrainer/layers/mol_attention_layer.cpp
  nntrainer/layers/rnn.cpp
  nntrainer/layers/rnncell.cpp
  nntrainer/layers/zoneout_lstmcell.cpp
Labels: bug

#1787 [gru] enable bias_hh, reset_after
  nntrainer/layers/common_properties.h
  nntrainer/layers/gru.cpp
  nntrainer/layers/gru.h
  nntrainer/layers/grucell.cpp
  nntrainer/layers/grucell.h
  packaging/unittest_layers_v2.tar.gz
  packaging/unittest_models.tar.gz
  test/input_gen/genLayerTests.py
  test/input_gen/genModelTests.py
  test/input_gen/transLayer.py
  test/unittest/layers/unittest_layers_gru.cpp
  test/unittest/layers/unittest_layers_grucell.cpp
  test/unittest/models/unittest_models_recurrent.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1788 [API] Add layer visitor for the model
  api/ccapi/include/model.h
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
Labels: PR/READY2MERGE

#1791 [Trivial] Tensor save changes /ofstream/ostream
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/utils/util_func.cpp
  nntrainer/utils/util_func.h
  test/unittest/unittest_util_func.cpp
Labels: PR/READY2MERGE

#1792 [Tensor] Add tensor cat
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  test/input_gen/transLayer_v2.py
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2GO

#1808 [tensor] Tensor pool request bug fix
  nntrainer/tensor/tensor_pool.cpp
Labels: bug

#1810 [layer] MAE layer bug fix
  Applications/Custom/mae_loss.cpp
Labels: RELEASE CRITICAL

#1811 [Graph] set trainable only if trainable
  nntrainer/graph/network_graph.cpp
Labels: RELEASE CRITICAL, PRIORITY/HIGH

#1794 [Spec] Change nntrainer install dir
  debian/nnstreamer-nntrainer.install
  meson_options.txt
  nnstreamer/tensor_filter/meson.build
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#1798 [Semantics] InitContext NumOutput is hint
  nntrainer/layers/concat_layer.cpp
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/mol_attention_layer.cpp
  nntrainer/layers/multiout_layer.cpp
  nntrainer/layers/split_layer.cpp
  nntrainer/layers/time_dist.cpp
  test/unittest/layers/layers_dependent_common_tests.cpp
  test/unittest/layers/layers_standalone_common_tests.cpp
Labels: PR/READY2MERGE

#1802 [Recurrent] Support connection for as_sequence
  nntrainer/compiler/recurrent_realizer.cpp
  nntrainer/compiler/recurrent_realizer.h
  test/unittest/compiler/unittest_realizer.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: RELEASE CRITICAL
