Repository nnstreamer/nntrainer, pull requests merged in 2021-07, with the labels that each got.

#1344 [Fix/trivial] Change rpm group description
  packaging/nntrainer.spec
Labels: RELEASE CRITICAL

#1321 [ Recurrent ] Implement Dropout for Recurrent Net
  api/ccapi/include/layer.h
  nntrainer/layers/gru.cpp
  nntrainer/layers/gru.h
  nntrainer/layers/layer_internal.h
  nntrainer/layers/lstm.cpp
  nntrainer/layers/lstm.h
  nntrainer/layers/rnn.cpp
  nntrainer/layers/rnn.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/utils/parse_util.cpp
Labels: PR/READY2MERGE

#1349 [Test/Bn] Add conv2d model test @open sesame 07/05 16:40
  packaging/unittest_models.tar.gz
  test/input_gen/genModelTests.py
  test/input_gen/transLayer.py
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1340 [Wait for #1339] [Resnet] Connect the model with cifar100 @open sesame 06/30 20:04
  Applications/Resnet/jni/cifar_dataloader.cpp
  Applications/Resnet/jni/cifar_dataloader.h
  Applications/Resnet/jni/main.cpp
Labels: pending, rebase required

#1343 [tests/modelfile] Enable modelfile unittest @open sesame 06/30 17:00
  nntrainer/app_context.cpp
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/compiler/ini_interpreter.h
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/loss/cross_entropy_loss_layer.h
  nntrainer/layers/loss/cross_entropy_sigmoid_loss_layer.h
  nntrainer/layers/loss/cross_entropy_softmax_loss_layer.h
  nntrainer/layers/loss/mse_loss_layer.h
  nntrainer/tensor/manager.h
  test/unittest/meson.build
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1353 [Fix] Weight initializer stddev calculation
  nntrainer/tensor/weight.cpp
Labels: PR/READY2MERGE

#1354 [Padding] Add padding2d prop header @open sesame 07/05 16:40
  nntrainer/layers/common_properties.h
Labels: PR/READY2MERGE

#1342 [docs] Add readme for resnet
  Applications/Resnet/README.md
Labels: PR/READY2MERGE

#1370 [Fix] File name sanitization
  Applications/SimpleShot/meson.build
  Applications/SimpleShot/tasks/tractor-turtle-squirrel-willow_tree-sunflower_10shot_seed-456_train.dat
  Applications/SimpleShot/tasks/tractor-turtle-squirrel-willow_tree-sunflower_1shot_seed-456_train.dat
  Applications/SimpleShot/tasks/tractor-turtle-squirrel-willow_tree-sunflower_20shot_seed-456_train.dat
  Applications/SimpleShot/tasks/tractor-turtle-squirrel-willow_tree-sunflower_5shot_seed-456_train.dat
  Applications/SimpleShot/tasks/tractor-turtle-squirrel-willow_tree-sunflower_seed-456_test.dat
Labels: PR/READY2MERGE

#1350 [test] Add common unittest for layers @open sesame 07/05 19:36
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_impl.cpp
  nntrainer/layers/layer_impl.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/loss/cross_entropy_loss_layer.h
  nntrainer/layers/loss/loss_layer.cpp
  nntrainer/layers/loss/loss_layer.h
  test/unittest/layers/layers_common_tests.cpp
  test/unittest/layers/layers_common_tests.h
  test/unittest/layers/layers_dependent_common_tests.cpp
  test/unittest/layers/layers_standalone_common_tests.cpp
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layer_node.cpp
  test/unittest/layers/unittest_layers_fully_connected.cpp
  test/unittest/layers/unittest_layers_impl.cpp
  test/unittest/layers/unittest_layers_input.cpp
  test/unittest/layers/unittest_layers_loss.cpp
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1356 [Padding] Add padding verification
  nntrainer/layers/common_properties.cpp
  test/unittest/unittest_common_properties.cpp
Labels: PR/READY2GO

#1388 [Resnet] Sync resnet app with validated model
  Applications/Resnet/jni/cifar_dataloader.cpp
  Applications/Resnet/jni/main.cpp
  nntrainer/layers/output_layer.cpp
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2MERGE

#1346 [CAPI] Add ml_train_model_get_input|output_dims
  api/capi/include/nntrainer.h
  api/capi/meson.build
  api/ccapi/include/model.h
  jni/Android.mk
  jni/prepare_ml-api.sh
  meson.build
  packaging/nntrainer.spec
Labels: PR/READY2GO, RELEASE CRITICAL

#1357 [Padding] Add padding compute function
  nntrainer/layers/common_properties.cpp
  test/unittest/unittest_common_properties.cpp
Labels: PR/READY2MERGE

#1366 [test] Add semantic tests for activation layer
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_activation.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1400 [spec/pkg] Bugfix for dependency
  packaging/nntrainer.spec
Labels: PR/READY2GO, RELEASE CRITICAL, bug

#1358 [Conv2D] Apply padding props to conv2d
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/conv2d_layer.h
  test/unittest/unittest_common_properties.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1369 [tests] Add more layer common unittests
  test/unittest/layers/layers_dependent_common_tests.cpp
  test/unittest/layers/layers_standalone_common_tests.cpp
Labels: PR/READY2GO, Refactor🏭

#1371 [CAPI] Propose dataset api sets
  api/capi/include/nntrainer.h
  api/ccapi/include/dataset.h
  api/nntrainer-api-common.h
Labels: PR/READY2GO, RELEASE CRITICAL

#1345 [CAPI] Propose save/load api @open sesame 07/05 16:40
  api/capi/include/nntrainer-tizen-internal.h
  api/capi/meson.build
  api/ccapi/include/model.h
  api/nntrainer-api-common.h
  packaging/nntrainer.spec
Labels: RELEASE CRITICAL

#1372 [dataset] Remove label data
  Applications/SimpleShot/task_runner.cpp
  Applications/SimpleShot/tasks/labels.dat
  api/ccapi/include/dataset.h
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/databuffer_file.cpp
  nntrainer/models/model_loader.cpp
  nntrainer/utils/parse_util.cpp
  test/ccapi/unittest_ccapi.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
  test/unittest/unittest_databuffer_file.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE

#1376 [dataset] Clean up dataset enums
  Applications/LogisticRegression/jni/main.cpp
  Applications/VGG/jni/main.cpp
  api/ccapi/include/dataset.h
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/databuffer_factory.cpp
  nntrainer/dataset/databuffer_factory.h
  nntrainer/dataset/databuffer_file.cpp
  nntrainer/dataset/databuffer_file.h
  nntrainer/dataset/databuffer_func.cpp
  nntrainer/dataset/databuffer_func.h
  nntrainer/dataset/databuffer_util.h
  nntrainer/models/model_loader.cpp
  nntrainer/models/neuralnet.cpp
  test/unittest/unittest_databuffer_file.cpp
Labels: PR/READY2MERGE

#1379 [dataset] split train / val / test databuffer @open sesame 07/15 15:00
  Applications/Custom/LayerClient/jni/main.cpp
  Applications/LogisticRegression/jni/main.cpp
  Applications/MNIST/jni/main.cpp
  Applications/ProductRatings/jni/main.cpp
  Applications/Resnet/jni/main.cpp
  Applications/SimpleShot/task_runner.cpp
  Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp
  Applications/TransferLearning/Draw_Classification/jni/main.cpp
  Applications/VGG/jni/main.cpp
  api/capi/include/nntrainer_internal.h
  api/capi/src/nntrainer.cpp
  api/ccapi/include/dataset.h
  api/ccapi/include/model.h
  api/ccapi/src/factory.cpp
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/databuffer_factory.cpp
  nntrainer/dataset/databuffer_factory.h
  nntrainer/dataset/databuffer_func.cpp
  nntrainer/dataset/databuffer_func.h
  nntrainer/models/model_loader.cpp
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
  nntrainer/utils/parse_util.cpp
  test/ccapi/unittest_ccapi.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: PR/READY2MERGE

#1385 [layer] Update GRU for layer_v2
  nntrainer/layers/gru.cpp
  nntrainer/layers/gru.h
  nntrainer/layers/lstm.cpp
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_gru.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1380 [dataset/cleanup] Remove type from dataset
  Applications/LogisticRegression/jni/main.cpp
  Applications/VGG/jni/main.cpp
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/databuffer_factory.cpp
  nntrainer/dataset/databuffer_file.cpp
  nntrainer/dataset/databuffer_file.h
  nntrainer/dataset/databuffer_func.cpp
  nntrainer/dataset/databuffer_func.h
  nntrainer/models/model_loader.cpp
  nntrainer/models/neuralnet.cpp
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
  test/unittest/unittest_databuffer_file.cpp
Labels: PR/READY2MERGE

#1386 [layer] Update preprocess layers for layerV2
  nntrainer/layers/preprocess_flip_layer.cpp
  nntrainer/layers/preprocess_flip_layer.h
  nntrainer/layers/preprocess_translate_layer.cpp
  nntrainer/layers/preprocess_translate_layer.h
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_preprocess.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1401 [devel] Add layer_devel/context to devel
  debian/nntrainer-dev.install
  nntrainer/layers/meson.build
  packaging/nntrainer.spec
Labels: PR/READY2GO

#1381 [dataset/cleanup] Remove usage from dataset impl
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/databuffer_file.cpp
  nntrainer/dataset/databuffer_file.h
  nntrainer/dataset/databuffer_func.cpp
  nntrainer/dataset/databuffer_func.h
  nntrainer/dataset/databuffer_util.h
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2MERGE

#1423 [application] Disable MNIST unittest
  Applications/MNIST/jni/main.cpp
Labels: bug

#1403 [layer] Enable time dist layer for V2
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/time_dist.cpp
  nntrainer/layers/time_dist.h
  nntrainer/tensor/tensor_dim.h
  test/unittest/unittest_nntrainer_modelfile.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1412 [unittest] Enable backbone unittests
  nntrainer/layers/layer_node.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1383 [Dataset/CAPI] implement dataset ctor
  api/capi/src/nntrainer.cpp
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
Labels: PR/READY2MERGE

#1391 [Dataset] Add random producer
  nntrainer/dataset/data_producers.h
  nntrainer/dataset/meson.build
  nntrainer/dataset/random_data_producers.cpp
  nntrainer/dataset/random_data_producers.h
Labels: PR/READY2MERGE

#1427 [ RNN ] Add mask for dropout
  nntrainer/layers/dropout.cpp
  nntrainer/layers/dropout.h
  nntrainer/layers/rnn.cpp
  nntrainer/layers/rnn.h
Labels: PR/READY2MERGE

#1441 [Android] Fix undefined definition @open sesame 07/27 13:50
  .gitignore
  Applications/TransferLearning/Draw_Classification/jni/Android.mk
  jni/prepare_ml-api.sh
Labels: PR/READY2GO

#1431 [ RNNT LOSS ] Add skeleton code for rnnt loss @open sesame 07/26 15:25
  Applications/Custom/LayerPlugin/layer_plugin_rnnt_loss_test.cpp
  Applications/Custom/LayerPlugin/meson.build
  Applications/Custom/meson.build
  Applications/Custom/rnnt_loss.cpp
  Applications/Custom/rnnt_loss.h
Labels: PR/READY2MERGE

#1392 [Dataset] Add test for the random dataproducer
  test/unittest/datasets/data_producer_common_tests.cpp
  test/unittest/datasets/data_producer_common_tests.h
  test/unittest/datasets/meson.build
  test/unittest/datasets/unittest_random_data_producers.cpp
  test/unittest/meson.build
Labels: PR/READY2GO

#1436 [CAPI] Deprecate old dataset apis
  api/capi/include/nntrainer.h
  meson.build
Labels: PR/READY2GO, RELEASE CRITICAL

#1438 [CAPI] Add ml_train_model_get_layer to internal
  api/capi/include/nntrainer-tizen-internal.h
Labels: PR/READY2GO

#1446 [CAPI] Change tensor dim -> information
  api/capi/include/nntrainer.h
Labels: RELEASE CRITICAL

#1444 [CAPI] Expose layer enums
  api/nntrainer-api-common.h
Labels: RELEASE CRITICAL
