Repository nnstreamer/nntrainer, pull requests merged in 2021-09, with the labels that each got.

#1537 [Trivial] delete no meaningful save/load test
  Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp
Labels: RELEASE CRITICAL, PR/READY2MERGE

#1535 [NeuralNet] Fix testset run
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
Labels: RELEASE CRITICAL

#1542 [ini] Implement input layers property @open sesame 09/08 14:17
  nntrainer/graph/graph_node.h
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  test/unittest/unittest_common_properties.cpp
Labels: RELEASE CRITICAL, PR/READY2MERGE

#1554 [bnlayer] Batch norm layer bug fix
  nntrainer/layers/bn_layer.h
Labels: RELEASE CRITICAL, PR/READY2MERGE

#1557 [Bug] Fix support inplace for distribute Layer
  nntrainer/layers/layer_node.cpp
Labels: RELEASE CRITICAL, PR/READY2MERGE

#1561 [Spec] Exclude generated coverage items
  packaging/nntrainer.spec
  test/unittest/datasets/unittest_databuffer.cpp
Labels: PR/READY2GO

#1569 Enable Saving props by delimiter '|'
  nntrainer/utils/node_exporter.h
  test/tizen_capi/unittest_tizen_capi.cpp
  test/tizen_capi/unittest_tizen_capi_layer.cpp
  test/tizen_capi/unittest_tizen_capi_optimizer.cpp
  test/unittest/unittest_base_properties.cpp
Labels: RELEASE CRITICAL

#1572 [Fix] upstream build fail
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_preprocess_flip.cpp
  test/unittest/layers/unittest_layers_preprocess_translate.cpp
Labels: PR/READY2MERGE

#1570 [Conv2d] Conv2d Padding Fix
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/pooling2d_layer.cpp
  test/unittest/unittest_common_properties.cpp
Labels: RELEASE CRITICAL, PR/READY2MERGE

#1571 [util] Remove parse_util.h
  debian/nntrainer-dev.install
  jni/Android.mk
  nntrainer/app_context.cpp
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/graph/graph_core.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/acti_func.cpp
  nntrainer/layers/activation_layer.cpp
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/layer_impl.cpp
  nntrainer/layers/layer_node.cpp
  nntrainer/models/model_loader.cpp
  nntrainer/optimizers/optimizer_devel.cpp
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor_dim.cpp
  nntrainer/utils/base_properties.cpp
  nntrainer/utils/base_properties.h
  nntrainer/utils/ini_wrapper.cpp
  nntrainer/utils/meson.build
  nntrainer/utils/node_exporter.h
  nntrainer/utils/parse_util.cpp
  nntrainer/utils/parse_util.h
  nntrainer/utils/props_util.h
  nntrainer/utils/util_func.cpp
  nntrainer/utils/util_func.h
  packaging/nntrainer.spec
  test/include/nntrainer_test_util.h
  test/unittest/unittest_nntrainer_layers.cpp
  test/unittest/unittest_util_func.cpp
Labels: RELEASE CRITICAL

#1577 [layer] Bug fixes for layers
  nntrainer/layers/bn_layer.h
  nntrainer/layers/flatten_layer.h
  nntrainer/layers/pooling2d_layer.cpp
Labels: PR/READY2GO, RELEASE CRITICAL

#1574 [unittest/models] Fix matching for models unittest
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1579 [gitignore] Update gitignore
  .gitignore
Labels: TRIVIAL

#1576 [Profiler] Enable profiler with fine grained profile
  Applications/MNIST/jni/main.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
Labels: PR/READY2MERGE

#1583 [Test] Update layer golden test format
  packaging/unittest_layers_v2.tar.gz
  test/input_gen/genLayerTests.py
  test/input_gen/recorder.py
  test/input_gen/transLayer.py
  test/unittest/layers/layers_golden_tests.cpp
Labels: PR/READY2MERGE

#1597 [Fix] gcc-7 has compile error
  test/unittest/unittest_nntrainer_tensor_pool.cpp
Labels: PR/READY2GO

#1584 [Test] Add bn layer training
  packaging/unittest_layers_v2.tar.gz
  test/input_gen/genLayerTests.py
  test/unittest/layers/unittest_layers_batch_normalization.cpp
Labels: PR/READY2MERGE
