Repository nnstreamer/nntrainer, pull requests merged in 2021-06, with the labels that each got.

#1228 [wait for #1210] [split/test] Added unittests for split layer
  api/ccapi/include/layer.h
  jni/Android.mk
  nntrainer/app_context.cpp
  nntrainer/layers/concat_layer.h
  nntrainer/layers/layer_factory.cpp
  nntrainer/layers/split_layer.cpp
  nntrainer/layers/split_layer.h
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO

#1230 [Fix] Prevent creating multiout for split
  nntrainer/graph/network_graph.cpp
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2MERGE

#1122 [Wait for #1121] [tflite] implement build operations in subgraph
  nntrainer/compiler/tflite_interpreter.cpp
Labels: PR/READY2GO

#1240 [Product Ratings] Fix inconsistent batch
  Applications/ProductRatings/jni/main.cpp
Labels: PR/READY2GO

#1245 [tflite] Update dependency from tflite to tf2lite
  debian/control
  meson.build
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#1146 [Tflite] Separate `tfopnode`
  jni/Android.mk
  nntrainer/compiler/meson.build
  nntrainer/compiler/tflite_interpreter.cpp
  nntrainer/compiler/tflite_opnode.cpp
  nntrainer/compiler/tflite_opnode.h
Labels: PR/READY2MERGE

#1252 [pkg] Reduce error tolerance for all builds @open sesame 06/08 10:52
  debian/rules
  meson.build
  meson_options.txt
  packaging/nntrainer.spec
  test/include/nntrainer_test_util.h
Labels: PR/READY2MERGE

#1232 [Fix] Initialize member variable
  Applications/ProductRatings/jni/main.cpp
  nntrainer/graph/graph_core.h
Labels: PR/READY2MERGE

#1149 [Android] Add tflite interpreter option
  jni/Android.mk
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/compiler/tflite_interpreter.cpp
  nntrainer/compiler/tflite_opnode.cpp
  nntrainer/compiler/tflite_opnode.h
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/utils/node_exporter.cpp
  nntrainer/utils/node_exporter.h
  test/unittest/compiler/unittest_interpreter.cpp
  test/unittest/unittest_base_properties.cpp
Labels: PR/READY2MERGE

#1195 [layer] Move flatten property to layerNode
  api/ccapi/src/factory.cpp
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  test/unittest/unittest_nntrainer_appcontext.cpp
Labels: PR/READY2MERGE

#1199 [meson] Enable tflite-interpreter by default
  debian/control
  meson.build
  meson_options.txt
  nntrainer/compiler/meson.build
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#1218 [Recorder] Add Input map generation
  test/input_gen/recorder.py
Labels: PR/READY2MERGE

#1262 [app] reduce Logistic regression application epochs
  Applications/LogisticRegression/res/LogisticRegression.ini
Labels: PR/READY2GO

#1214 [Layer] Add permute layer scaffolding
  api/ccapi/include/layer.h
  jni/Android.mk
  nntrainer/app_context.cpp
  nntrainer/layers/meson.build
  nntrainer/layers/permute_layer.cpp
  nntrainer/layers/permute_layer.h
  nntrainer/tensor/tensor_dim.cpp
  nntrainer/utils/base_properties.h
  test/unittest/unittest_base_properties.cpp
Labels: PR/READY2GO

#1207 [layer] Move distribute to LayerNode
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/graph/graph_node.h
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/time_dist.h
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO

#1169 [Permute] Implement peripheral functions
  nntrainer/layers/permute_layer.cpp
  nntrainer/layers/permute_layer.h
  nntrainer/utils/node_exporter.h
Labels: PR/READY2GO

#1221 [ LSTM ] Add More Unit Test Cases
  packaging/unittest_models.tar.gz
  test/input_gen/genModelTests.py
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1219 [Recorder] Add multiout equivalent in transLayer @open sesame 06/09 15:12
  test/input_gen/genModelTests.py
  test/input_gen/recorder.py
  test/input_gen/transLayer.py
Labels: PR/READY2MERGE

#1209 [ RNN ] Add unittest case & return_sequence
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/lstm.cpp
  nntrainer/layers/rnn.cpp
  nntrainer/layers/rnn.h
  packaging/unittest_models.tar.gz
  test/input_gen/genModelTests.py
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1173 [Permute] Add permute layer forward/backward
  nntrainer/layers/permute_layer.cpp
  nntrainer/layers/permute_layer.h
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2MERGE

#1241 [SplitLayer] Support flexible dimension @open sesame 06/03 12:41
  Applications/ProductRatings/jni/main.cpp
  Applications/ProductRatings/jni/meson.build
  Applications/ProductRatings/res/product_ratings_model.ini
  nntrainer/layers/split_layer.cpp
  nntrainer/layers/split_layer.h
  nntrainer/tensor/tensor.cpp
Labels: PR/READY2MERGE

#1237 [APP] Add tensorflow based product rating
  Applications/ProductRatings/Tensorflow/embedding.py
  Applications/ProductRatings/Tensorflow/product_ratings.py
  Applications/ProductRatings/jni/main.cpp
Labels: PR/READY2MERGE

#1261 [Layer] Add requireLabel() function
  Applications/SimpleShot/layers/centroid_knn.h
  nntrainer/layers/layer_internal.h
  nntrainer/layers/loss_layer.h
Labels: PR/READY2MERGE

#1266 [Trivial] Fix NDK warning -Wbraced-scalar-init
  nntrainer/layers/lstm.cpp
Labels: TRIVIAL

#1224 [ RNN ] Add Multi-Layer RNN Unit Tests
  nntrainer/layers/lstm.cpp
  nntrainer/layers/rnn.cpp
  packaging/unittest_models.tar.gz
  test/input_gen/genModelTests.py
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1249 [api] Added api dependency in pc files
  .gitignore
  Applications/Custom/LayerClient/jni/Android.mk
  Applications/KNN/jni/Android.mk
  Applications/LogisticRegression/jni/Android.mk
  Applications/MNIST/jni/Android.mk
  Applications/ProductRatings/jni/Android.mk
  Applications/ReinforcementLearning/DeepQ/jni/Android.mk
  Applications/TransferLearning/CIFAR_Classification/jni/Android.mk
  Applications/TransferLearning/Draw_Classification/jni/Android.mk
  Applications/VGG/jni/Android.mk
  api/capi/capi-ml-training.pc.in
  api/capi/include/platform/ml-api-common.h
  api/ccapi/ccapi-ml-training.pc.in
  jni/Android.mk
  jni/prepare_ml-api-common.sh
  jni/prepare_openblas.sh
  meson.build
Labels: PR/READY2MERGE

#1264 [Trivial] Change return -> retval
  Applications/SimpleShot/layers/centering.h
  Applications/SimpleShot/layers/centroid_knn.h
  Applications/SimpleShot/layers/l2norm.h
  nntrainer/app_context.h
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/compiler/tflite_opnode.h
  nntrainer/graph/graph_node.h
  nntrainer/layers/common_properties.h
  nntrainer/layers/layer_internal.h
  nntrainer/tensor/tensor_dim.h
  nntrainer/tensor/var_grad.h
  nntrainer/utils/base_properties.h
  nntrainer/utils/ini_wrapper.h
  nntrainer/utils/parse_util.h
  nntrainer/utils/util_func.h
  test/unittest/compiler/unittest_interpreter.cpp
Labels: PR/READY2MERGE

#1273 [deb/pkg] Update lower tolerance bug + increase timeouts
  debian/rules
  test/ccapi/meson.build
  test/tizen_capi/meson.build
Labels: PR/READY2MERGE

#1267 [Docs] Update custom documentation for loss layer
  Applications/Custom/LayerClient/jni/pow.cpp
  Applications/Custom/README.md
Labels: PR/READY2MERGE

#1265 [layer context] Propose layer context and layer_devel
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
Labels: PR/READY2GO

#1278 [split layer] Initialize class member bugfix
  nntrainer/layers/split_layer.h
Labels: PR/READY2GO, bug

#1272 [layer] Move name to LayerNode
  Applications/Custom/LayerPlugin/layer_plugin_test.cpp
  Applications/SimpleShot/test/simpleshot_centering_test.cpp
  Applications/SimpleShot/test/simpleshot_centroid_knn.cpp
  Applications/SimpleShot/test/simpleshot_l2norm_test.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/plugged_layer.h
  nntrainer/layers/time_dist.cpp
  nntrainer/utils/node_exporter.cpp
  nntrainer/utils/node_exporter.h
  test/unittest/compiler/unittest_interpreter.cpp
  test/unittest/meson.build
  test/unittest/unittest_base_properties.cpp
  test/unittest/unittest_nntrainer_appcontext.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1287 [addition] Bug fix addition layer calcDerivative
  nntrainer/layers/addition_layer.cpp
  nntrainer/layers/concat_layer.cpp
Labels: Refactor🏭

#1282 [docs] Update docs for tflite version
  docs/getting-started.md
Labels: TRIVIAL

#1285 [context] Layer context creation scaffolding
  Applications/Custom/LayerClient/jni/Android.mk
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.h
  nntrainer/tensor/manager.h
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1290 [manager] Support request Tensors and Weights
  nntrainer/layers/layer_context.h
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
  nntrainer/tensor/var_grad.h
  nntrainer/tensor/weight.h
Labels: PR/READY2MERGE, Refactor🏭

#1299 [neuralnet] Bug fix for graph usage
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2GO, bug

#1291 Implement get input dimension get output dimension in layernode
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/layer_node.h
  nntrainer/models/neuralnet.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1293 [Layer] Add const to the layer::getName()
  api/ccapi/include/layer.h
  nntrainer/graph/graph_node.h
  nntrainer/layers/layer_node.h
Labels: PR/READY2MERGE, Refactor🏭

#1206 [Props] Add concept of empty to property
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/layer_node.h
  nntrainer/utils/base_properties.h
  nntrainer/utils/node_exporter.h
  test/unittest/unittest_base_properties.cpp
Labels: PR/READY2MERGE

#1292 [Layer] Scaffold layer impl
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_impl.cpp
  nntrainer/layers/layer_impl.h
  nntrainer/layers/meson.build
  test/unittest/layers/unittest_layers_fully_connected.cpp
  test/unittest/layers/unittest_layers_impl.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1300 [ GRU ] Add GRU Unittest
  nntrainer/layers/gru.cpp
  nntrainer/layers/gru.h
  nntrainer/layers/lstm.cpp
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  packaging/unittest_models.tar.gz
  test/input_gen/genModelTests.py
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2GO

#1268 [Custom/Loss] Add scaffolding for loss example
  Applications/Custom/LayerClient/jni/meson.build
  Applications/Custom/LayerPlugin/layer_plugin_mae_loss_test.cpp
  Applications/Custom/LayerPlugin/layer_plugin_pow_test.cpp
  Applications/Custom/LayerPlugin/meson.build
  Applications/Custom/mae_loss.cpp
  Applications/Custom/mae_loss.h
  Applications/Custom/meson.build
  Applications/Custom/pow.cpp
  Applications/Custom/pow.h
Labels: PR/READY2MERGE

#1296 [wait for #1295] [graph] Support creating RunLayerContext
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.h
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
Labels: PR/READY2MERGE, Refactor🏭

#1295 [manager] Add support for request Inputs/outputs
  nntrainer/layers/layer_context.h
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
Labels: PR/READY2MERGE, Refactor🏭

#1298 [Layer] Add trainable prop
  nntrainer/layers/common_properties.h
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_impl.cpp
  nntrainer/layers/layer_impl.h
Labels: PR/READY2MERGE, Refactor🏭

#1270 [Plugin/Test] Add preset plugin for general test
  Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp
  Applications/Custom/LayerPlugin/layer_plugin_common_test.h
  Applications/Custom/LayerPlugin/layer_plugin_mae_loss_test.cpp
  Applications/Custom/LayerPlugin/layer_plugin_pow_test.cpp
  Applications/Custom/LayerPlugin/meson.build
  Applications/Custom/mae_loss.h
Labels: pending

#1301 [networkgraph] Network graph updated for Layer V2
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_internal.h
  nntrainer/layers/layer_node.h
Labels: PR/READY2GO, Refactor🏭

#1302 [network] Remove check for double activation
  nntrainer/graph/network_graph.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1305 [manager] Support initialization/allocation of weights
  nntrainer/graph/network_graph.cpp
  nntrainer/tensor/manager.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1306 [AppContext] Integrate layer-devel @open sesame 06/22 16:38
  Applications/Custom/LayerPlugin/layer_plugin_test.cpp
  Applications/Custom/pow.cpp
  nntrainer/app_context.cpp
  nntrainer/app_context.h
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/layers/plugged_layer.h
  test/unittest/layers/layers_common_tests.cpp
  test/unittest/layers/layers_common_tests.h
Labels: PR/READY2MERGE, Refactor🏭

#1311 [manager] Memory allocation for non-weight tensors
  nntrainer/graph/network_graph.cpp
  nntrainer/tensor/manager.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1312 [layernode] Layer interfaces support in LayerNode
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_impl.cpp
  nntrainer/layers/layer_impl.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  test/unittest/layers/unittest_layers_impl.cpp
Labels: PR/READY2MERGE, Refactor🏭

#1313 [layer context] Add interfaces for setBatch
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/tensor/var_grad.h
  nntrainer/tensor/weight.h
Labels: PR/READY2MERGE, Refactor🏭

#1317 [layernode/impl] Add properties to Layer Node and Impl
  nntrainer/layers/layer_impl.cpp
  nntrainer/layers/layer_impl.h
  nntrainer/layers/layer_node.h
Labels: PR/READY2GO, Refactor🏭

#1320 [CustomLoss] Update example
  Applications/Custom/LayerClient/jni/Android.mk
  Applications/Custom/LayerClient/jni/main.cpp
  Applications/Custom/LayerClient/jni/meson.build
  Applications/Custom/LayerClient/res/custom_layer_client.ini
  Applications/Custom/mae_loss.cpp
Labels: PR/READY2MERGE

#1323 [layernode] Move activation to LayerNode @open sesame 06/22 18:12
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/acti_func.h
  nntrainer/layers/activation_layer.cpp
  nntrainer/layers/activation_layer.h
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/time_dist.cpp
  nntrainer/utils/parse_util.cpp
Labels: Refactor🏭

#1332 [layernode] Update throw to retval in setProperty
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
Labels: PR/READY2GO, Refactor🏭

#1335 [Resnet/skeleton] Add helper functions
  .gitignore
  Applications/Resnet/jni/cifar_dataloader.h
  Applications/Resnet/jni/main.cpp
  Applications/Resnet/res/prepare_dataset.sh
Labels: PR/OK2GO
