Repository nnstreamer/nntrainer, pull requests merged in 2021-03, with the labels that each got.

#956 [Util] Delete internal namespace @open sesame 02/19 17:28
  nntrainer/nntrainer_error.h
Labels: PR/READY2MERGE

#934 [loss] Allow no loss in the model @open sesame 02/19 17:43
  .gitignore
  docs/configuration-ini.md
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/loss_layer.cpp
  nntrainer/layers/loss_layer.h
  nntrainer/models/model_loader.cpp
  nntrainer/models/model_loader.h
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
  nntrainer/utils/parse_util.cpp
  test/test_models/models/mnist_inf.ini
  test/unittest/unittest_nntrainer_modelfile.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#983 [dataset/unittest] Bug fix for segmentation fault
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
Labels: RELEASE CRITICAL, bug

#987 [CAPI] Add mapping to newly added enum
  api/capi/src/nntrainer_util.cpp
  test/tizen_capi/unittest_tizen_capi_layer.cpp
Labels: RELEASE CRITICAL

#985 Fix/svace issue 210308
  Applications/SimpleShot/task_runner.cpp
  test/ccapi/unittest_ccapi.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: PR/READY2MERGE, RELEASE CRITICAL

#994 [app] Set env to run the app test
  Applications/TransferLearning/Draw_Classification/jni/meson.build
Labels: bug

#996 [model] Update batch size check
  nntrainer/models/neuralnet.cpp
Labels: RELEASE CRITICAL, bug

#999 [Meson/Clean] remove duplicating deps
  Applications/Custom/LayerPlugin/meson.build
  Applications/SimpleShot/test/meson.build
  Applications/meson.build
Labels: TRIVIAL

#1015 [SE] Make coverage build runnable
  packaging/nntrainer.spec
Labels: PR/READY2MERGE, RELEASE CRITICAL

#1009 [model] Move layers out of model
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
Labels: PR/READY2MERGE

#1022 [docs] Minor indentation fix
  docs/memory-management.md
Labels: TRIVIAL

#988 [ LAYER ] Add backwarding of Embedding Layer
  nntrainer/layers/embedding.cpp
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO

#1001 [weights] Bug fix + lazy allocation
  nntrainer/layers/bn_layer.cpp
  nntrainer/layers/conv2d_layer.cpp
  nntrainer/layers/fc_layer.cpp
  nntrainer/models/neuralnet.cpp
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/var_grad.h
  nntrainer/tensor/weight.h
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO, RELEASE CRITICAL, bug

#1029 [test/bug] Bug fix for layers unittest
  nntrainer/tensor/var_grad.h
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO, RELEASE CRITICAL, bug

#1004 [ Application ] Add Embedding Layer Training Example @open sesame 03/23 12:08
  Applications/Embedding/Tensorflow/embedding.py
  Applications/Embedding/jni/Android.mk
  Applications/Embedding/jni/Application.mk
  Applications/Embedding/jni/main.cpp
  Applications/Embedding/jni/meson.build
  Applications/Embedding/res/Embedding.ini
  Applications/Embedding/res/embedding_input.txt
  Applications/meson.build
Labels: PR/READY2GO

#1037 [TestHub] Produce xml output for gtest
  Applications/SimpleShot/test/meson.build
  Applications/TransferLearning/Draw_Classification/jni/meson.build
  test/ccapi/meson.build
  test/tizen_capi/meson.build
  test/unittest/meson.build
Labels: PR/READY2MERGE, RELEASE CRITICAL

#1056 [graph/ini] Support for default input_layers
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  test/unittest/unittest_nntrainer_models.cpp
Labels: RELEASE CRITICAL

#1057 Fix/coverity issue 210329
  Applications/Custom/LayerPlugin/layer_plugin_test.cpp
  Applications/TransferLearning/Draw_Classification/jni/main.cpp
Labels: RELEASE CRITICAL

#1053 [graph] Bug fix for no loss
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/loss_layer.h
Labels: RELEASE CRITICAL

#1034 [rpm] Fix nnstreamer dependency @opensesame 03/30 01:49
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#1058 fix/analysishub_issue_210330
  test/unittest/unittest_nntrainer_appcontext.cpp
Labels: RELEASE CRITICAL
