Repository nnstreamer/nntrainer, pull requests merged in 2021-02, with the labels that each got.

#883 [CAPI/acr] Update tizen capi header
  api/ccapi/include/layer.h
  api/nntrainer-api-common.h
  nntrainer/app_context.cpp
  nntrainer/layers/layer_factory.cpp
Labels: RELEASE CRITICAL

#894 [Fix] Resolve static init order fiasco
  nntrainer/app_context.cpp
Labels: PR/READY2GO

#916 [blas] Add missing return
  nntrainer/tensor/blas_interface.cpp
Labels: TRIVIAL, bug

#918 [adam] Reduce temporary memory allocation
  nntrainer/optimizers/adam.cpp
  test/unittest/unittest_nntrainer_layers.cpp
Labels: enhancement

#933 [app_context] Resolve build issue with gcc5
  nntrainer/app_context.cpp
Labels: RELEASE CRITICAL, bug

#890 [Weight] Cleanup train argument for initialize gradient
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/var_grad.cpp
  nntrainer/tensor/var_grad.h
  nntrainer/tensor/weight.cpp
  nntrainer/tensor/weight.h
Labels: PR/READY2MERGE

#949 [Fix] Update lazy alloc ctor to lazy alloc
  nntrainer/tensor/tensor.cpp
Labels: PR/READY2GO, bug

#952 [Build] change dependency to nnstreamer api @open sesame 02/17 18:27
  debian/control
  meson.build
  packaging/nntrainer.spec
Labels: PR/READY2GO

#961 [Fix/Svace] Add try catch to the top level app
  Applications/Custom/LayerClient/jni/main.cpp
Labels: RELEASE CRITICAL
