Repository nnstreamer/nntrainer, pull requests merged in 2021-04, with the labels that each got.

#1049 [graph] More refactors for graph + bug fix @open sesame 04/01 11:12
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
Labels: PR/READY2GO, bug

#1079 [IniInterpreter] Add section2layer
  nntrainer/app_context.h
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/compiler/ini_interpreter.h
Labels: PR/READY2MERGE

#1080 [Wait for #1079] [IniInterpreter] Add ini backbone deserialization
  nntrainer/app_context.cpp
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/utils/util_func.cpp
  nntrainer/utils/util_func.h
Labels: PR/READY2MERGE

#1087 [Ini] Propose ini wrapper
  jni/Android.mk
  nntrainer/utils/ini_wrapper.cpp
  nntrainer/utils/ini_wrapper.h
  nntrainer/utils/meson.build
Labels: PR/READY2MERGE, TRIVIAL

#1095 [manager] disable inference_memory_opt
  nntrainer/tensor/manager.h
Labels: PR/READY2MERGE

#1096 [Fix] Multiout layer calcDerivative initialize
  nntrainer/layers/output_layer.cpp
Labels: PR/READY2MERGE

#1115 Handle Uninitialized scalar variable issue @open sesame 04/20 17:02
  nntrainer/layers/lstm.h
Labels: PR/READY2MERGE

#1088 [Wait for #1087] [Ini] Propose ini wrapper 2 @open sesame 04/22 13:18
  nntrainer/utils/ini_wrapper.cpp
  nntrainer/utils/ini_wrapper.h
Labels: PR/READY2MERGE, TRIVIAL

#1132 [Preprocess] Set default trainable to false @open sesame 04/22 12:39
  api/ccapi/include/layer.h
  nntrainer/app_context.cpp
  nntrainer/layers/preprocess_flip_layer.h
  nntrainer/layers/preprocess_translate_layer.h
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#1089 [Wait for #1088, #1132] [Ini] Remove IniTestWrapper @open sesame 04/22 18:26
  test/ccapi/unittest_ccapi.cpp
  test/include/nntrainer_test_util.h
  test/nntrainer_test_util.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
  test/unittest/unittest_nntrainer_graph.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE, TRIVIAL

#1074 [ TIME DIST ] Modify graph to recognize time distribute layer @open sesame 04/26 21:11
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/time_dist.cpp
  nntrainer/layers/time_dist.h
  nntrainer/models/model_loader.cpp
  test/unittest/unittest_nntrainer_layers.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2GO

#1091 [Ini/Serialize] Implement logic to serialize
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/utils/ini_wrapper.cpp
  nntrainer/utils/ini_wrapper.h
  test/unittest/compiler/unittest_interpreter.cpp
Labels: PR/READY2MERGE

#1128 [README] Replace nnsuite to nnstreamer @open sesame 04/24 11:31
  README.md
Labels: PR/READY2MERGE

#1138 [Docs] Fix doxygen
  api/ccapi/include/model.h
  api/ccapi/include/optimizer.h
  nntrainer/layers/layer_node.h
  nntrainer/tensor/lazy_tensor.cpp
  nntrainer/tensor/lazy_tensor.h
  nntrainer/tensor/var_grad.h
  test/unittest/unittest_nntrainer_lazy_tensor.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/OK2GO

#1139 [doxygen] Var_Grad doxygen fix
  nntrainer/tensor/var_grad.h
Labels: TRIVIAL

#1134 [Competibility] Change test reference tolerance @open sesame 04/22 18:25
  test/ccapi/unittest_ccapi.cpp
Labels: PR/READY2GO

#1148 [Fix] Reorder error in layernode
  nntrainer/layers/layer_node.h
Labels: PR/READY2GO
