Repository nnstreamer/nntrainer, pull requests merged in 2021-05, with the labels that each got.

#1141 [graph] Bug fix for duplicate output connections
  nntrainer/graph/network_graph.cpp
Labels: bug

#1155 [Doxygen] Add doxygen to tensordim
  nntrainer/tensor/tensor_dim.h
Labels: PR/READY2GO, TRIVIAL

#1156 [TensorDim/Tensor] Update transpose relates
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_dim.cpp
  nntrainer/tensor/tensor_dim.h
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2GO

#1106 [Layer/props] Convert name to props
  nntrainer/layers/common_properties.h
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/fc_layer.h
  nntrainer/layers/layer.cpp
  nntrainer/layers/layer_internal.h
  nntrainer/utils/base_properties.h
  nntrainer/utils/node_exporter.h
  test/unittest/unittest_properties.cpp
Labels: PR/READY2GO

#1107 [IniSerializer] Add `serialize` to ini
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/utils/ini_wrapper.cpp
  nntrainer/utils/ini_wrapper.h
  test/unittest/compiler/unittest_interpreter.cpp
Labels: PR/READY2GO

#1171 fix/coverity_issue_210507
  Applications/Embedding/jni/main.cpp
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Labels: PR/READY2MERGE

#1109 [Skeleton] Add Tflite interpreter skeleton @open sesame 05/10 12:54
  jni/Android.mk
  nntrainer/compiler/meson.build
  nntrainer/compiler/tflite_interpreter.cpp
  nntrainer/compiler/tflite_interpreter.h
Labels: PR/READY2MERGE, TRIVIAL

#1159 [Props] Separate base_propeties to a source
  jni/Android.mk
  nntrainer/utils/base_properties.cpp
  nntrainer/utils/base_properties.h
  nntrainer/utils/meson.build
Labels: PR/READY2MERGE

#1166 [Props] Add cast operator
  nntrainer/utils/base_properties.h
  test/unittest/unittest_properties.cpp
Labels: PR/READY2MERGE

#1167 [Props] Change is_valid function signature
  nntrainer/layers/common_properties.h
  nntrainer/utils/base_properties.h
  test/unittest/unittest_properties.cpp
Labels: PR/READY2GO, TRIVIAL

#1181 [test] Resolve golden data of size 0
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2MERGE, bug

#1183 [Fix] Add compiler complaining types
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2GO

#1184 [Update] update daily build badge
  README.md
Labels: TRIVIAL

#1161 [Props] Add dimension property
  nntrainer/utils/base_properties.cpp
  nntrainer/utils/base_properties.h
  test/unittest/unittest_properties.cpp
Labels: PR/READY2MERGE

#1112 [Tflite] Implement TfOpNode
  nntrainer/compiler/tflite_interpreter.cpp
  nntrainer/layers/layer_internal.h
  test/unittest/compiler/unittest_interpreter.cpp
Labels: PR/READY2MERGE

#1116 [Tflite] Implement serializing opcode
  nntrainer/compiler/tflite_interpreter.cpp
Labels: PR/READY2MERGE

#1196 [Svace] Fix dangling reference issue
  nntrainer/graph/network_graph.cpp
Labels: PR/READY2GO

#1165 [Props] Add vector/array handler
  nntrainer/utils/base_properties.cpp
  nntrainer/utils/base_properties.h
  nntrainer/utils/node_exporter.h
  test/unittest/unittest_properties.cpp
Labels: PR/READY2MERGE

#1182 [graph] Add graph core class
  nntrainer/graph/graph_core.cpp
  nntrainer/graph/graph_core.h
  nntrainer/graph/graph_node.h
  nntrainer/graph/meson.build
  nntrainer/graph/network_graph.h
  nntrainer/layers/layer_node.h
Labels: PR/READY2MERGE

#1193 [model] Model inference should not catch throw
  nntrainer/models/neuralnet.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2GO, RELEASE CRITICAL, bug

#1190 [time_dist] setProperty for time distribution layer
  nntrainer/layers/time_dist.h
Labels: PR/READY2GO, bug

#1194 [android] Fix android build @open sesame 05/18 13:25
  .gitignore
  jni/Android.mk
Labels: bug

#1118 [Tflite] Implement `BuildTensors`
  nntrainer/compiler/tflite_interpreter.cpp
  test/test_models/models/simple_fc.ini
  test/unittest/compiler/unittest_interpreter.cpp
Labels: PR/READY2MERGE

#1185 [Props] Add Name validator and unittest
  jni/Android.mk
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/meson.build
  test/unittest/meson.build
  test/unittest/unittest_base_properties.cpp
  test/unittest/unittest_common_properties.cpp
Labels: PR/READY2GO

#1215 [Addition] fix forwarding
  nntrainer/layers/addition_layer.cpp
Labels: PR/READY2GO

#1197 [Test/models] prepare to support non-linear models
  test/input_gen/genModelTests.py
  test/input_gen/recorder.py
  test/input_gen/transLayer.py
Labels: rebase required

#1157 [VarGrad] Add clone Transpose
  nntrainer/tensor/var_grad.cpp
  nntrainer/tensor/var_grad.h
Labels: PR/READY2GO

#1179 [ LSTM ] Backwarding Implementation
  nntrainer/layers/lstm.cpp
  nntrainer/layers/lstm.h
  test/unittest/unittest_nntrainer_layers.cpp
Labels: PR/READY2MERGE

#1222 [App] Make embedding golden data optional
  Applications/Embedding/jni/main.cpp
Labels: PR/READY2MERGE
