Repository nnstreamer/nntrainer, pull requests merged in 2022-02, with the labels that each got.

#1829 [lstm] remove timestep property
  nntrainer/compiler/recurrent_realizer.cpp
  nntrainer/layers/lstm.cpp
  nntrainer/layers/lstm.h
  packaging/unittest_models_v2.tar.gz
  test/input_gen/genModelsRecurrent_v2.py
  test/input_gen/transLayer_v2.py
  test/unittest/compiler/unittest_realizer.cpp
  test/unittest/models/unittest_models_recurrent.cpp
Labels: PR/READY2MERGE

#1834 [ SAVE/LOAD ] save / load optimizer variables
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
  nntrainer/tensor/weight.h
Labels: PR/READY2MERGE

#1830 [Wait for #1829] [lstm] implement bidirectional lstm forward
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/lstm.cpp
  nntrainer/layers/lstm.h
  test/input_gen/genModelsRecurrent_v2.py
  test/input_gen/transLayer_v2.py
  test/unittest/models/unittest_models_recurrent.cpp
Labels: PR/READY2MERGE

#1838 [api] Update model inference API
  api/ccapi/include/model.h
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
Labels: TRIVIAL

#1790 [optim] Add pytorch reference for adam @open sesame 12/22 19:01
  nntrainer/optimizers/adam.cpp
  nntrainer/optimizers/adam.h
Labels: PR/READY2GO

#1846 [layer] LSTM weight array size fix
  nntrainer/layers/lstm.h
Labels: bug, RELEASE CRITICAL
