Repository nnstreamer/nntrainer, pull requests merged in 2023-02, with the labels that each got.

#2076 [Utils] Add log timestamp type
  nntrainer/nntrainer_logger.cpp
  nntrainer/nntrainer_logger.h
Labels: rebase required

#2055 (Wait for #2098) [SWAP] Implement cache policy
  nntrainer/tensor/cache_pool.cpp
Labels: rebase required, Need Review

#2122 [Trivial] Fix svace and coverity issue @open sesame 02/21 14:35
  nntrainer/tensor/manager.h
  nntrainer/utils/profiler.h
Labels: PRIORITY/HIGH

#2107 [Application] Merge LSTM to Layers
  Applications/LSTM/README.md
  Applications/LSTM/tensorflow/tensor_lstm.py
  Applications/Layers/PyTorch/LSTM.py
Labels: PR/READY2MERGE

#2117 [Propose][GitAction] Review Request Auto labeler @open sesame 02/21 13:48
  .github/workflows/labeler.yml
Labels: PR/READY2MERGE

#2130 [GitAction] Fix Gitaction Auto Labeler
  .github/workflows/Upload.yml
  .github/workflows/labeler.yml
Labels: Need Review
