Repository nnstreamer/nntrainer, pull requests merged in 2023-09, with the labels that each got.

#2305 [blas/neon] SGEMM Neon execution for any M value
  nntrainer/tensor/blas_interface.cpp
  nntrainer/tensor/blas_neon.cpp
Labels: Need Review

#2292 [sub-plugin] Modify synchronization mechanism between push_data and getSample
  nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
  nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh
Labels: PR/READY2GO, PR/READY2MERGE, M2 release

#2301 [Tensor] Quantized Tensor (Int 4) with Scale
  api/ccapi/include/tensor_dim.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_dim.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
  test/unittest/unittest_nntrainer_tensor_nhwc.cpp
  test/unittest/unittest_nntrainer_tensor_pool.cpp
Labels: Need Review

#2310 [Application] Setup meson file for libyolov2_loss_layer.so @open sesame 09/13 18:48
  Applications/YOLO/jni/meson.build
  Applications/YOLO/jni/yolo_v2_loss.cpp
  debian/nntrainer-applications.install
  packaging/nntrainer.spec
Labels: PR/READY2GO, M2 release

#2320 Revert "[Release] NNTrainer v0.5.1 release"
  debian/changelog
  meson.build
  packaging/nntrainer.spec
Labels: Need Review

#2319 [Application] bugfix for YOLO version 2
  Applications/YOLO/jni/main.cpp
  Applications/YOLO/jni/reorg_layer.h
Labels: Need Review, M2 release

#2322 [Svace] Fix Ahub issues
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
Labels: Need Review
