Repository nnstreamer/nntrainer, pull requests merged in 2023-10, with the labels that each got.

#2309 [Tensor] Dequantize tensor in forwarding FC layer
  nntrainer/graph/network_graph.h
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_wrap_specs.h
  nntrainer/tensor/weight.cpp
  nntrainer/tensor/weight.h
  test/unittest/layers/layers_golden_tests.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
  test/unittest/unittest_nntrainer_tensor_nhwc.cpp
Labels: Need Review

#2326 [neon] Optmize sgemv
  nntrainer/tensor/blas_neon.cpp
Labels: Need Review

#2303 [Tensor/trivial] Erase redundant code
  nntrainer/tensor/tensor.cpp
Labels: PR/READY2GO

#2272 [Cifar100] Fix Cifar100 Dataloader @open sesame 08/28 20:44
  Applications/utils/datagen/cifar/cifar_dataloader.cpp
  Applications/utils/datagen/cifar/cifar_dataloader.h
Labels: PR/READY2MERGE

#2331 [neon] Optimize sgemv 2.0
  nntrainer/tensor/blas_neon.cpp
Labels: Need Review

#2312 [Tensor] Read quantized tensor from a binary file
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: Need Review

#2330 [#Wait for #2312][Tensor] Optimize dequantize operation
  nntrainer/layers/fc_layer.cpp
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  test/unittest/unittest_nntrainer_tensor.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
  test/unittest/unittest_nntrainer_tensor_nhwc.cpp
Labels: rebase required

#2348 [unittest] remove empty test case
  test/unittest/memory/unittest_cache_pool.cpp
Labels: Need Review

#2345 [neon] Support scopy for multiple dataTypes in neon
  nntrainer/tensor/blas_interface.cpp
  nntrainer/tensor/blas_interface.h
  nntrainer/tensor/blas_neon.cpp
  nntrainer/tensor/blas_neon.h
  nntrainer/tensor/tensor.cpp
Labels: Need Review

#2352 [gtest] Fix gtest error assessing logic
  test/unittest/layers/layers_golden_tests.cpp
Labels: Need Review
