Repository nnstreamer/nntrainer, pull requests merged in 2023-03, with the labels that each got.

#2136 replace strerror with strerror_r
  Applications/Tizen_native/CustomShortcut/src/data.c
  Applications/Tizen_native/CustomShortcut/src/main.c
  Applications/utils/datagen/cifar/cifar_dataloader.cpp
  nntrainer/compiler/tflite_interpreter.cpp
  nntrainer/models/model_loader.cpp
  nntrainer/tensor/swap_device.cpp
  nntrainer/utils/ini_wrapper.cpp
  nntrainer/utils/util_func.h
Labels: TRIVIAL, PRIORITY/HIGH, Need Review

#2113 [Wait for #2109][FlatBuffer] Add nntrainer_schema.fbs @open sesame 03/13 15:00
  nntrainer/compiler/meson.build
  nntrainer/compiler/nntrainer_schema.fbs
Labels: PR/READY2GO

#2142 [Trivial] Typo Error
  nntrainer/compiler/ini_interpreter.cpp
  nntrainer/compiler/input_realizer.cpp
  nntrainer/compiler/input_realizer.h
  nntrainer/layers/pooling2d_layer.cpp
  nntrainer/utils/node_exporter.h
Labels: Need Review
