Repository nnstreamer/nntrainer, pull requests merged in 2023-06, with the labels that each got.

#2211 [Trivial] Fix Typo
  api/capi/include/nntrainer_internal.h
  api/capi/src/nntrainer.cpp
  test/tizen_capi/unittest_tizen_capi_lr_scheduler.cpp
  test/tizen_capi/unittest_tizen_capi_optimizer.cpp
  test/unittest/unittest_nntrainer_lr_scheduler.cpp
Labels: PR/READY2MERGE

#2206 [Wait for nnstreamer #4080][nnstreamer][trainer] Add getting model stats information @open sesame 06/08 11:20
  nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
  nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh
Labels: BUILD/CI, Need Review

#2228 [Trivial] Fix typo error
  nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
  nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh
  nntrainer/models/dynamic_training_optimization.cpp
  nntrainer/models/dynamic_training_optimization.h
  nntrainer/models/model_loader.cpp
  nntrainer/models/model_loader.h
Labels: PR/READY2MERGE

#2232 [Application] Transfer learning example on Resnet-18
  Applications/Resnet/jni/main.cpp
Labels: Need Review

#2235 [ Bug ] Fix the bug read the weight for batch normalization layer
  nntrainer/tensor/manager.cpp
Labels: RELEASE CRITICAL
