Repository nnstreamer/nntrainer, pull requests merged in 2023-11, with the labels that each got.

#2347 [bugfix] Android ndk-build error fix
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
Labels: PR/READY2MERGE

#2288 [TensorDim] Fix TensorDim constructor
  api/ccapi/include/tensor_dim.h
  nntrainer/tensor/tensor_dim.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
  test/unittest/unittest_nntrainer_tensor_nhwc.cpp
Labels: PR/READY2GO

#2364 [trivial/bugfix] Add `inference_only_option` in multi_head_attention
  test/unittest/layers/unittest_layers_multi_head_attention.cpp
Labels: Need Review

#2365 [Sub-plugin] Refactoring sub-plugin class
  nnstreamer/tensor_trainer/tensor_trainer_nntrainer.cc
  nnstreamer/tensor_trainer/tensor_trainer_nntrainer.hh
Labels: DISCUSSION

#2369 [Ahub] Fix AnalysisHub defects
  Applications/LLaMA/jni/main.cpp
  Applications/LLaMA/jni/rms_norm.h
  Applications/LLaMA/jni/rotary_embedding.h
  Applications/Multi_input/jni/main.cpp
  Applications/Multi_input/jni/multi_loader.cpp
  Applications/PicoGPT/jni/main.cpp
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
  Applications/YOLOv3/jni/det_dataloader.cpp
  Applications/YOLOv3/jni/main.cpp
  Applications/YOLOv3/jni/yolo_v3_loss.cpp
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/manager.h
  nntrainer/tensor/tensor.cpp
Labels: PR/READY2MERGE

#2374 [neon/bugfix] Fix ewva function
  nntrainer/tensor/blas_neon.cpp
Labels: Need Review

#2368 [Tensor] Initial Draft of Tensor Version 2
  debian/nntrainer-dev.install
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/meson.build
  nntrainer/tensor/src_shared_tensor.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
  packaging/nntrainer.spec
  test/unittest/meson.build
  test/unittest/unittest_nntrainer_tensor_v2.cpp
  test/unittest/unittest_nntrainer_tensor_v2_fp16.cpp
Labels: PR/READY2MERGE

#2372 [Exporter] Update node_exporter
  nntrainer/utils/node_exporter.cpp
  nntrainer/utils/node_exporter.h
Labels: PR/READY2MERGE
