Repository nnstreamer/nntrainer, pull requests merged in 2024-10, with the labels that each got.

#2741 [bugfix] Fix memcheck in CacheLoader unit tests @open sesame 10/02 10:47
  test/unittest/memory/unittest_cache_loader.cpp
Labels: bug, PR/READY2MERGE

#2738 [gpu/enhance] Utility for registering Blas kernels during initialization @open sesame 10/02 11:44
  nntrainer/cl_context.cpp
  nntrainer/cl_context.h
  nntrainer/layers/layer_node.cpp
  nntrainer/tensor/cl_operations/blas_kernel_strings.h
  nntrainer/tensor/cl_operations/blas_kernels.cpp
  nntrainer/tensor/cl_operations/blas_kernels.h
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
  nntrainer/tensor/cl_operations/meson.build
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: Need Review

#2736 [bugfix] Fix sgemv_cl function call from blas_kernel_interface @open sesame 14/10 10:42
  nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
Labels: BUILD/CI

#2744 [bugfix/blas] Fixed sgemm_cl pointer check @open sesame 10/04 17:23
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
Labels: PR/READY2MERGE

#2748 [Wait for 2736 & 2744 ][update/gpu] Update FC layer on GPU with latest pipeline changes
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/fc_layer_cl.cpp
  nntrainer/layers/cl_layers/meson.build
Labels: PR/READY2MERGE

#2737 [Filter] util to get nth info
  nnstreamer/tensor_filter/tensor_filter_nntrainer.cc
Labels: PR/READY2MERGE

#2739 [coverity] fix coverity issue @open sesame 10/02 11:44
  nntrainer/tensor/blas_neon.cpp
Labels: PR/READY2MERGE, PR/OK2GO

#2756 Fix for compiling with testcoverage
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#2753 [ GPU ] fix return by reference to return by value
  nntrainer/cl_context.cpp
  nntrainer/cl_context.h
Labels: PR/READY2MERGE

#2742 [header] add missing headers @open sesame 10/02 11:44
  Applications/Multi_input/jni/multi_loader.cpp
  Applications/YOLOv3/jni/det_dataloader.cpp
  nntrainer/utils/util_simd.cpp
Labels: PR/READY2MERGE

#2755 [unittest] add negative cases & delete meaningless cases
  test/tizen_capi/unittest_tizen_capi_layer.cpp
  test/unittest/compiler/unittest_realizer.cpp
  test/unittest/datasets/unittest_iteration_queue.cpp
  test/unittest/layers/layers_dependent_common_tests.cpp
  test/unittest/layers/layers_golden_tests.cpp
  test/unittest/memory/unittest_cache_pool.cpp
  test/unittest/models/models_golden_test.cpp
  test/unittest/unittest_base_properties.cpp
  test/unittest/unittest_common_properties.cpp
  test/unittest/unittest_nntrainer_internal.cpp
  test/unittest/unittest_nntrainer_lr_scheduler.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
  test/unittest/unittest_nntrainer_tensor_nhwc.cpp
Labels: PR/READY2MERGE

#2758 [Test] Add unit tests for newly added tensor type @open sesame 10/17 17:36
  nntrainer/tensor/tensor.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#2760 [Loss] Remove Empty KLD Loss files @open sesame 10/18 12:10
  nntrainer/layers/loss/kld_loss_layer.cpp
  nntrainer/layers/loss/kld_loss_layer.h
  nntrainer/layers/loss/meson.build
Labels: PR/READY2MERGE

#2764 [Unittest] re-activate the deactivated unittest
  test/ccapi/unittest_ccapi.cpp
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_reduce_mean.cpp
  test/unittest/models/meson.build
  test/unittest/models/unittest_models.cpp
Labels: PR/READY2MERGE

#2768 [ unittest/modelfile ] Add res directory when compiled for android unittest
  test/unittest/unittest_nntrainer_modelfile.cpp
  tools/android_test.sh
Labels: Need Review, UnitTest

#2766 [Unittest] Add constant DerivativeLossLayer unittest
  test/unittest/layers/unittest_layers_loss.cpp
Labels: PR/READY2MERGE, UnitTest

#2769 [ unittest/modelfile ] Fix backbone_n_15 @open sesame 10/17 17:36
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE, UnitTest

#2686 [ Layers ] Bug Fix for NHWC Support
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/flatten_layer.cpp
Labels: PR/READY2MERGE

#2771 [ unittest/modelfile ] Fix backbone_20 @open sesame 10/25 10:21
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE, UnitTest

#2772 [ Wait for #2771 ][unittest/modelfile] Fix nntrainerIniTest @open sesame 10/28 13:48
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: rebase required, UnitTest

#2761 [ GPU ] move `initBlaseClKernels()` to registerer
  nntrainer/cl_context.cpp
  nntrainer/layers/layer_node.cpp
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: PR/READY2MERGE

#2688 [GPU/OpenCL] Adding map/unmap feature for buffer @open sesame 10/29 21:51
  nntrainer/opencl/opencl_buffer.cpp
  nntrainer/opencl/opencl_buffer.h
  nntrainer/opencl/opencl_command_queue_manager.cpp
  nntrainer/opencl/opencl_command_queue_manager.h
  nntrainer/opencl/opencl_loader.cpp
  nntrainer/opencl/opencl_loader.h
Labels: BUILD/CI
