Repository nnstreamer/nntrainer, pull requests merged in 2024-03, with the labels that each got.

#2477 [TensorV2] Create a mask of dropout, filter, and zoneout @open sesame 02/26 12:23
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE, PR/OK2GO

#2492 [util] Add numpy file reader
  Applications/utils/meson.build
  Applications/utils/npy_reader/meson.build
  Applications/utils/npy_reader/npy_reader.cpp
  Applications/utils/npy_reader/npy_reader.h
Labels: PR/READY2MERGE

#2483 [TensorV2] Tensor element summation by axes feature
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE, PR/OK2GO

#2487 [TensorV2] Average Tensor element by axes @open sesame 03/07 10:42
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE

#2499 [Trivial/CI] sync cpp-linter version with clang-format
  .github/workflows/cpp_linter.yml
Labels: PR/READY2MERGE

#2497 [TensorV2] Add functions to split and concatenate tensors @open sesame 03/07 10:42
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE

#2504 [build] Updated Android build script for OpenCl inclusion
  tools/package_android.sh
Labels: PR/READY2MERGE

#2489 [TensorV2] Add utility member functions to TensorV2 class @open sesame 03/07 10:42
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE

#2502 [ neon ] Hgemv transpose biggerkernel
  nntrainer/tensor/blas_neon.cpp
Labels: PR/READY2MERGE

#2498 [Layer] Remove Tensor setDataType() usage
  nntrainer/layers/layer_normalization_layer.cpp
  nntrainer/layers/loss/cross_entropy_softmax_loss_layer.cpp
  nntrainer/layers/lstm.cpp
  nntrainer/layers/lstmcell.cpp
  nntrainer/layers/lstmcell_core.cpp
  nntrainer/layers/multi_head_attention_layer.cpp
Labels: PR/READY2MERGE

#2508 [Coverity] Fix the coverity issue
  api/capi/include/nntrainer_internal.h
  nntrainer/utils/node_exporter.cpp
Labels: PR/READY2MERGE

#2509 [coverity] fix coverity issues
  nntrainer/tensor/task_executor.cpp
  nntrainer/utils/node_exporter.cpp
Labels: PR/READY2MERGE

#2506 Bump actions/checkout in Ubuntu Meson build & test
  .github/workflows/ubuntu_clean_meson_build.yml
Labels: PR/READY2MERGE

#2510 Use parameterized test in `NamePropertyTest`
  test/unittest/unittest_common_properties.cpp
Labels: PR/READY2MERGE

#2513 [ coverity ] Fix coverity issue
  test/unittest/layers/layers_golden_tests.cpp
  test/unittest/models/unittest_models_multiout.cpp
  test/unittest/unittest_nntrainer_graph.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE

#2507 Fix minor error in github action
  .github/workflows/pylint.yml
  .github/workflows/ubuntu_clean_meson_build.yml
Labels: rebase required

#2511 [Coverity] Fix the coverity issue
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/layer_node.cpp
  nntrainer/models/neuralnet.cpp
  test/unittest/compiler/unittest_tflite_export.cpp
  test/unittest/unittest_nntrainer_models.cpp
Labels: PR/READY2MERGE

#2516 [coverity] fix coverity issue @open sesame 03/25 15:19
  test/unittest/models/unittest_models_recurrent.cpp
Labels: PR/READY2MERGE

#2512 [coverity] fix coverity issue
  nntrainer/dataset/iteration_queue.cpp
  test/unittest/layers/layers_common_tests.h
Labels: PR/READY2MERGE

#2515 [ coverity ] Fix Coverity issue
  test/unittest/layers/layers_golden_tests.cpp
Labels: PR/READY2MERGE

#2518 [coverity] fix coverity issues
  nntrainer/dataset/iteration_queue.cpp
  test/unittest/models/models_test_utils.cpp
Labels: PR/READY2MERGE

#2522 [Trivial] Disable cpp-linter action's clang-format
  .github/workflows/cpp_linter.yml
Labels: PR/READY2MERGE

#2524 [Coverity] Fix coverity issues
  api/capi/src/nntrainer.cpp
  nntrainer/utils/node_exporter.cpp
Labels: PR/READY2MERGE

#2523 [svace] fix svace issues
  Applications/utils/jni/bitmap_helpers.cpp
  nntrainer/dataset/raw_file_data_producer.cpp
  nntrainer/layers/gru.cpp
  nntrainer/layers/lstm.cpp
  nntrainer/layers/rnn.cpp
  nntrainer/utils/util_func.cpp
  test/unittest/compiler/unittest_tflite_export.cpp
Labels: Need Review
