Repository nnstreamer/nntrainer, pull requests merged in 2024-12, with the labels that each got.

#2749 [Wait for #2803][Mixed Precision] Fix gradient clipping logic @open sesame 12/02 09:37
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
Labels: PR/READY2MERGE

#2802 [UTIL] fix the bug in nntr parallel run @open sesame 12/02 17:11
  nntrainer/utils/nntr_threads.cpp
Labels: PR/READY2MERGE

#2740 [ccapi] add return last output option in incremental inference @open sesame 12/04 16:19
  api/ccapi/include/model.h
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
Labels: BUILD/CI, rebase required

#2818 [Tensor] Binary-code-based quantized tensor
  api/ccapi/include/tensor_dim.h
  meson.build
  meson_options.txt
  nntrainer/tensor/bcq_tensor.cpp
  nntrainer/tensor/bcq_tensor.h
  nntrainer/tensor/meson.build
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor_dim.cpp
Labels: Need Review

#2819 [Bugfix] Read & save quantized tensor data.
  nntrainer/tensor/bcq_tensor.cpp
  nntrainer/tensor/bcq_tensor.h
  nntrainer/tensor/tensor.cpp
Labels: Need Review

#2823 [ Meson ] BCQTensor dependency is added for Android build
  nntrainer/tensor/meson.build
Labels: Need Review

#2821 docs: fix typo
  api/nntrainer-api-common.h
Labels: Need Review

#2824 Quantizer class to perform quantization
  debian/nntrainer-dev.install
  nntrainer/tensor/meson.build
  nntrainer/tensor/quantizer.cpp
  nntrainer/tensor/quantizer.h
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#2811 [ GPU ] Removing PLUGGABLE flag and its action from official cl layers.
  nntrainer/layers/cl_layers/swiglu_cl.cpp
  nntrainer/layers/cl_layers/transpose_cl.cpp
Labels: PR/READY2MERGE

#2829 [ BCQ ] Add a feature to enable BCQ tensor as a weight type (cont.)
  nntrainer/layers/layer_context.h
Labels: PR/READY2MERGE

#2825 [ minor ] bugfix in printing error log (model_commo_properties / LossScale)
  nntrainer/models/model_common_properties.cpp
Labels: PR/READY2MERGE

#2836 [hotfix] Fix if-else condition for FSU
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2MERGE
