Repository nnstreamer/nntrainer, pull requests merged in 2024-02, with the labels that each got.

#2428 [TensorV2] Refactoring TensorBase pointer to shared_ptr
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE

#2432 [CI] Update cpp-linter's option - extensions
  .github/workflows/cpp_linter.yml
Labels: PR/READY2MERGE

#2453 [bugfix] Fix the creation of SharedDataTensor
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
Labels: bug

#2443 [TensorV2] Add addition operation structure
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE

#2454 [ bug ] Use fp16 when applying sqrt_i
  nntrainer/tensor/tensor.cpp
Labels: bug, PR/READY2MERGE

#2445 [TensorV2] Add subtraction operation structure
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE

#2457 [blas] Optimize gemv and gemm for float16 data type
  nntrainer/tensor/blas_interface.cpp
Labels: PR/READY2MERGE

#2464 [CI] Update cpp-linter ci (false file-annotations)
  .github/workflows/cpp_linter.yml
  nntrainer/dataset/func_data_producer.h
Labels: PR/READY2MERGE

#2461 [Test] strided tensor multiplication unit test
  test/unittest/unittest_nntrainer_tensor_v2.cpp
  test/unittest/unittest_nntrainer_tensor_v2_fp16.cpp
Labels: PR/READY2MERGE

#2471 [TensorV2] Add power function and Gauss error function
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE

#2466 [Test] TensorV2 division unit test
  test/unittest/unittest_nntrainer_tensor_v2.cpp
  test/unittest/unittest_nntrainer_tensor_v2_fp16.cpp
Labels: Need Review

#2451 [ fp16 ] Fix to avoid build error / compiler warnings
  meson.build
  meson_options.txt
  nntrainer/tensor/meson.build
  nntrainer/utils/meson.build
  tools/package_android.sh
Labels: PR/READY2MERGE

#2478 [CI] static prebuild_ci : from (nnstreamer)
  .github/workflows/static.check.scripts/Doxyfile.prj
  .github/workflows/static.check.scripts/cppcheck.sh
  .github/workflows/static.check.scripts/doxygen-build.sh
  .github/workflows/static.check.scripts/doxygen-tag.sh
  .github/workflows/static.check.scripts/executable.sh
  .github/workflows/static.check.scripts/flawfinder.sh
  .github/workflows/static.check.scripts/hardcoded-path.sh
  .github/workflows/static.check.scripts/indent.sh
  .github/workflows/static.check.scripts/misspelling.sh
  .github/workflows/static.check.scripts/newline.sh
  .github/workflows/static.check.scripts/nobody.sh
  .github/workflows/static.check.scripts/prohibited-words.sh
  .github/workflows/static.check.scripts/prohibited-words.txt
  .github/workflows/static.check.scripts/pylint.sh
  .github/workflows/static.check.scripts/rpm-spec.sh
  .github/workflows/static.check.scripts/shellcheck.sh
  .github/workflows/static.check.scripts/signed-off-by.sh
  .github/workflows/static.check.scripts/sloccount.sh
  .github/workflows/static.check.scripts/timestamp.sh
  .github/workflows/static.check.yml
Labels: PR/READY2MERGE

#2472 [TensorV2] Add dot product support
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/READY2MERGE

#2469 [TensorV2] Subtraction support @open sesame 02/20 11:30
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/tensor_v2.cpp
Labels: PR/READY2MERGE

#2475 [TensorV2] Add Transpose Support for Tensor
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_v2.cpp
  nntrainer/tensor/tensor_v2.h
Labels: PR/OK2GO

#2481 [SPEC] support neon enable option
  nntrainer/tensor/meson.build
  nntrainer/utils/meson.build
  packaging/nntrainer.spec
Labels: Need Review

#2480 [AVX] Added VCVT (between floating-point and integer) AVX support for x86 architecture
  meson.build
  meson_options.txt
  nntrainer/tensor/blas_avx.cpp
  nntrainer/tensor/blas_avx.h
  nntrainer/tensor/blas_interface.cpp
  nntrainer/tensor/meson.build
Labels: PR/READY2MERGE

#2490 [Android] Fix for cxxflags
  jni/Android.mk.in
  jni/meson.build
Labels: PR/READY2MERGE

#2493 [Coverity] Fix the coverity issue
  test/unittest/unittest_nntrainer_tensor_v2.cpp
Labels: Need Review
