Repository nnstreamer/nntrainer, pull requests merged in 2024-04, with the labels that each got.

#2526 [Coverity] Fix coverity issues
  nntrainer/dataset/iteration_queue.cpp
  nntrainer/dataset/raw_file_data_producer.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/tensor/cache_elem.h
  test/unittest/models/unittest_models.cpp
Labels: PR/READY2MERGE

#2527 [ HGEMM ] Draft of kernel-based hgemm
  nntrainer/tensor/hgemm/hgemm.h
  nntrainer/tensor/hgemm/hgemm_common.h
  nntrainer/tensor/hgemm/hgemm_kernel_4x4.h
  nntrainer/tensor/hgemm/hgemm_kernel_8x8.h
  nntrainer/tensor/hgemm/hgemm_kernel_pack.h
  nntrainer/tensor/hgemm/hgemm_util.h
  nntrainer/tensor/meson.build
Labels: Need Review

#2530 Fix typo in test
  test/tizen_capi/unittest_tizen_capi_dataset.cpp
  test/tizen_capi/unittest_tizen_capi_layer.cpp
  test/tizen_capi/unittest_tizen_capi_lr_scheduler.cpp
  test/unittest/compiler/unittest_compiler.cpp
  test/unittest/unittest_base_properties.cpp
  test/unittest/unittest_nntrainer_appcontext.cpp
  test/unittest/unittest_nntrainer_exe_order.cpp
  test/unittest/unittest_nntrainer_graph.cpp
  test/unittest/unittest_nntrainer_internal.cpp
  test/unittest/unittest_nntrainer_lazy_tensor.cpp
  test/unittest/unittest_nntrainer_modelfile.cpp
  test/unittest/unittest_nntrainer_models.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
  test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp
Labels: PR/READY2MERGE

#2521 [Layer] Create Depthwise 2D Convolution
  nntrainer/layers/depthwise_conv2d_layer.h
Labels: PR/READY2MERGE

#2537 [layer] multi batch incremental forwarding
  nntrainer/layers/addition_layer.cpp
Labels: PR/READY2MERGE

#2538 Fix typo in docs
  Applications/MNIST/README.md
  README.md
  docs/configuration-ini.md
Labels: PR/READY2MERGE

#2533 Use parameterized test in `AppContextTest`
  test/unittest/unittest_nntrainer_appcontext.cpp
Labels: PR/READY2MERGE

#2532 [application] update llm generate function
  Applications/LLaMA/jni/main.cpp
Labels: PR/READY2MERGE

#2542 [neuralnet] enable multi batch incremental inference
  nntrainer/models/neuralnet.cpp
Labels: Need Review

#2543 [Docs] Fix readme in Applications dir
  Applications/Custom/README.md
  Applications/Custom/mae_loss.h
  Applications/README.md
  Applications/YOLO/jni/reorg_layer.cpp
  Applications/YOLO/jni/reorg_layer.h
Labels: PR/READY2MERGE

#2536 [Wait for #2532][application] add repetition_penalty to generate func @open sesame 04/06 10:40
  Applications/LLaMA/jni/main.cpp
Labels: PR/READY2MERGE

#2544 Add ELU activation function @open sesame 04/15 20:15
  api/ccapi/include/layer.h
  nntrainer/layers/acti_func.h
  nntrainer/layers/common_properties.h
  test/unittest/unittest_nntrainer_activations.cpp
Labels: PR/READY2MERGE

#2547 [Docs] add yolov3 readme file
  Applications/YOLOv3/readme.md
Labels: PR/READY2MERGE

#2548 [neuralnet] bugfix multi batch incremental inference
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2MERGE

#2545 Add Softplus activation function @open sesame 04/15 10:41
  nntrainer/layers/acti_func.h
  nntrainer/layers/common_properties.h
  test/unittest/unittest_nntrainer_activations.cpp
Labels: rebase required

#2551 ci / remove cpp-linter's false positive reports.
  .github/workflows/cpp_linter.yml
Labels: PR/READY2MERGE

#2552 Add Mish activation function
  api/ccapi/include/layer.h
  nntrainer/layers/acti_func.h
  nntrainer/layers/common_properties.h
  test/unittest/unittest_nntrainer_activations.cpp
Labels: PR/READY2MERGE

#2546 [LoRA] add alpha parameter to LoRA (fc_layer) @open sesame 04/23 09:33
  nntrainer/layers/common_properties.h
  nntrainer/layers/fc_layer.cpp
  nntrainer/layers/fc_layer.h
  nntrainer/utils/node_exporter.cpp
  nntrainer/utils/node_exporter.h
Labels: PR/READY2MERGE

#2557 [bugfix] Fix build issues when fp16 is enabled
  nntrainer/layers/acti_func.h
Labels: Need Review

#2554 [hgemm] hgemm noTrans with 1x4 kernel
  nntrainer/tensor/hgemm/hgemm.cpp
  nntrainer/tensor/hgemm/hgemm.h
  nntrainer/tensor/hgemm/hgemm_kernel_1x4.h
  test/unittest/unittest_nntrainer_tensor_neon_fp16.cpp
Labels: Need Review

#2553 [Application] Bugfix in LLaMA Application
  Applications/LLaMA/jni/main.cpp
Labels: PR/READY2MERGE
