Repository nnstreamer/nntrainer, pull requests merged in 2024-07, with the labels that each got.

#2656 [Trivial] Fix Typo
  nntrainer/app_context.cpp
  nntrainer/dataset/data_iteration.h
  nntrainer/dataset/data_producer.h
  nntrainer/dataset/databuffer.h
  nntrainer/dataset/dir_data_producers.cpp
  nntrainer/dataset/random_data_producers.cpp
  nntrainer/layers/preprocess_l2norm_layer.h
  nntrainer/layers/split_layer.cpp
Labels: PR/READY2MERGE

#2639 [Layer] Introduce `upsample2d` layer
  api/ccapi/include/layer.h
  nntrainer/app_context.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/meson.build
  nntrainer/layers/upsample2d_layer.cpp
  nntrainer/layers/upsample2d_layer.h
  packaging/unittest_layers.tar.gz
  test/input_gen/gen_layer_tests.py
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_upsample2d.cpp
Labels: PR/READY2MERGE

#2659 [CI] Add PR review from clang-format
  .github/workflows/cpp_linter.yml
Labels: PR/READY2MERGE

#2664 [Tensor] Remove NaN check for integer
  nntrainer/tensor/tensor.cpp
Labels: Need Review

#2657 [FP16][Tensor] Remove unnecessary copy on save
  nntrainer/tensor/tensor.cpp
Labels: PR/READY2MERGE

#2611 [layer] added start/end dimension in flatten layer
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/flatten_layer.cpp
  nntrainer/layers/flatten_layer.h
  test/unittest/layers/unittest_layers_flatten.cpp
Labels: PR/READY2MERGE

#2651 [GPU/OpenCL] Initial version of Reshape Layer with OpenCL ops
  api/ccapi/include/layer.h
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/meson.build
  nntrainer/layers/cl_layers/reshape_cl.cpp
  nntrainer/layers/cl_layers/reshape_cl.h
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  test/input_gen/gen_layer_tests.py
  test/jni/Android.mk
  test/unittest/layers/unittest_layers_reshape_cl.cpp
Labels: rebase required, PR/READY2MERGE

#2666 [GPU/OpenCL] Moving Addition kernel to Tensor Directory @open sesame 07/04 09:01
  nntrainer/layers/cl_layers/addition_layer_cl.cpp
  nntrainer/layers/cl_layers/addition_layer_cl.h
  nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
  nntrainer/tensor/cl_operations/blas_kernel_interface.h
  test/unittest/layers/unittest_layers_addition_cl.cpp
Labels: PR/READY2MERGE

#2648 [ blas/OpenCL ] SGEMM OpenCL kernels added
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
  nntrainer/tensor/cl_operations/blas_kernels.cpp
  nntrainer/tensor/cl_operations/blas_kernels.h
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: PR/READY2MERGE

#2669 [ CI ] modify android build test in action
  .github/workflows/android.yml
Labels: PR/READY2MERGE

#2670 README: add openssf best practice badge.
  README.md
Labels: PR/READY2MERGE

#2631 [GPU/OpenCL] Initial version of RMSNorm Layer
  api/ccapi/include/layer.h
  api/nntrainer-api-common.h
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/meson.build
  nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
  nntrainer/layers/cl_layers/rmsnorm_layer_cl.h
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  test/input_gen/gen_layer_tests.py
  test/jni/Android.mk
  test/unittest/layers/unittest_layers_rmsnorm_cl.cpp
Labels: rebase required, PR/READY2MERGE

#2672 [build] Added third party to include directories
  nntrainer/opencl/meson.build
Labels: PR/READY2MERGE

#2658 [Layer] add tanh-based approximate gelu activation function
  nntrainer/layers/acti_func.h
  nntrainer/layers/common_properties.h
Labels: PR/READY2MERGE

#2674 Remove dangerous dummy meson dep
  api/capi/meson.build
  api/ccapi/meson.build
  meson.build
  nntrainer/meson.build
Labels: PR/READY2MERGE

#2677 [meson] fix typo error and add encoder option
  Applications/LLaMA/jni/main.cpp
  meson.build
  meson_options.txt
Labels: PR/READY2MERGE

#2675 [bugfix] Resolves Android build warnings
  nntrainer/layers/layer_node.h
  nntrainer/layers/lstm.h
  nntrainer/models/neuralnet.h
  nntrainer/tensor/cache_pool.h
  nntrainer/tensor/manager.h
  test/unittest/unittest_nntrainer_appcontext.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
  test/unittest/unittest_nntrainer_tensor_nhwc.cpp
Labels: PR/READY2MERGE

#2676 [ trivial/util ] Change name swish -> swiglu
  nntrainer/utils/util_simd.cpp
  nntrainer/utils/util_simd.h
  nntrainer/utils/util_simd_neon.cpp
  nntrainer/utils/util_simd_neon.h
Labels: PR/READY2MERGE

#2665 [Layer] Add missing activation type
  nntrainer/layers/common_properties.h
Labels: PR/READY2MERGE

#2678 [trivial] remove unnecessary code
  test/unittest/models/models_test_utils.cpp
Labels: PR/READY2MERGE

#2679 [Android] Add android test script
  tools/android_test.sh
Labels: PR/READY2MERGE

#2680 [Application] Bug fix in RL example @open seasame 07/25 13:55
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Labels: PR/READY2MERGE

#2683 fix: incorrect C/C++ preprocessor macro
  Applications/PicoGPT/jni/main.cpp
Labels: PR/READY2MERGE

#2667 [GPU/OpenCL] Initial version of Concat Layer with OpenCL ops
  api/ccapi/include/layer.h
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/concat_cl.cpp
  nntrainer/layers/cl_layers/concat_cl.h
  nntrainer/layers/cl_layers/meson.build
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  test/jni/Android.mk
  test/unittest/layers/unittest_layers_concat_cl.cpp
Labels: rebase required, Need Review
