Repository nnstreamer/nntrainer, pull requests merged in 2024-11, with the labels that each got.

#2777 [GPU/OpenCL] Remove duplicate macro definition.
  nntrainer/layers/cl_layers/addition_layer_cl.h
Labels: Need Review

#2778 [Tensor] Parameterized constructor with TensorBase
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#2779 [Tensor] Update with scale factor support for quantized data types
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_base.h
Labels: PR/READY2MERGE

#2786 [ unittest ] Enable more modelfile TCs
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE

#2787 [Application] add README for LLaMA application @open sesame 11/07 16:01
  Applications/LLaMA/README.md
  Applications/LLaMA/jni/merges.txt
  Applications/LLaMA/jni/vocab.json
Labels: PR/READY2MERGE

#2788 [ unittest ] Fix modelfile TCs @open sesame 11/07 16:09
  test/unittest/unittest_nntrainer_modelfile.cpp
Labels: PR/READY2MERGE

#2710 [Layer] add "add layer"
  api/ccapi/include/layer.h
  api/nntrainer-api-common.h
  debian/nntrainer-dev.install
  nntrainer/app_context.cpp
  nntrainer/layers/add_layer.cpp
  nntrainer/layers/add_layer.h
  nntrainer/layers/meson.build
  nntrainer/layers/operation_layer.h
  packaging/nntrainer.spec
  packaging/unittest_models_v2.tar.gz
  test/ccapi/unittest_ccapi.cpp
  test/input_gen/genModelTests_v2.py
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_add.cpp
  test/unittest/models/unittest_models.cpp
Labels: PR/READY2MERGE

#2724 [Wait for #2710][Layer] add "subtract layer" @open sesame 11/06 18:29
  api/ccapi/include/layer.h
  api/nntrainer-api-common.h
  nntrainer/app_context.cpp
  nntrainer/layers/meson.build
  nntrainer/layers/subtract_layer.cpp
  nntrainer/layers/subtract_layer.h
  test/ccapi/unittest_ccapi.cpp
  test/input_gen/genModelTests_v2.py
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_subtract.cpp
  test/unittest/models/unittest_models.cpp
Labels: rebase required

#2789 [Graph] rename variable & function names for clarity @open sesame 11/07 21:30
  Applications/Custom/mae_loss.cpp
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/acti_func.h
  nntrainer/layers/activation_layer.cpp
  nntrainer/layers/cl_layers/reshape_cl.cpp
  nntrainer/layers/identity_layer.cpp
  nntrainer/layers/input_layer.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/multiout_layer.cpp
  nntrainer/layers/reshape_layer.cpp
  nntrainer/layers/time_dist.cpp
Labels: PR/READY2MERGE

#2725 [Wait for #2724][Layer] add "multiply layer" @open sesame 11/12 10:52
  api/ccapi/include/layer.h
  api/nntrainer-api-common.h
  nntrainer/app_context.cpp
  nntrainer/layers/meson.build
  nntrainer/layers/multiply_layer.cpp
  nntrainer/layers/multiply_layer.h
  test/ccapi/unittest_ccapi.cpp
  test/input_gen/genModelTests_v2.py
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_multiply.cpp
  test/unittest/models/unittest_models.cpp
Labels: PR/READY2MERGE, Need Review

#2726 [Wait for #2725][Layer] add "divide layer"
  api/ccapi/include/layer.h
  api/nntrainer-api-common.h
  nntrainer/app_context.cpp
  nntrainer/layers/divide_layer.cpp
  nntrainer/layers/divide_layer.h
  nntrainer/layers/meson.build
  test/input_gen/genModelTests_v2.py
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_divide.cpp
  test/unittest/models/unittest_models.cpp
Labels: PR/READY2MERGE

#2750 [GPU/OpenCL] Initial version of Transpose (all axes) with OpenCL ops.
  Applications/LLaMA/jni/transpose_layer.h
  api/ccapi/include/layer.h
  api/nntrainer-api-common.h
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/meson.build
  nntrainer/layers/cl_layers/transpose_cl.cpp
  nntrainer/layers/cl_layers/transpose_cl.h
  nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
  nntrainer/tensor/cl_operations/blas_kernel_interface.h
  nntrainer/tensor/cl_operations/blas_kernel_strings.h
  nntrainer/tensor/cl_operations/blas_kernels.cpp
  nntrainer/tensor/cl_operations/blas_kernels.h
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
  test/input_gen/gen_layer_tests.py
  test/jni/Android.mk
  test/unittest/layers/unittest_layers_transpose_cl.cpp
Labels: PR/READY2MERGE

#2770 [gpu/blas] sgemv_noTrans kernel and unit tests @open sesame 10/29 21:54
  nntrainer/cl_context.cpp
  nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
  nntrainer/tensor/cl_operations/blas_kernel_strings.h
  nntrainer/tensor/cl_operations/blas_kernels.cpp
  nntrainer/tensor/cl_operations/blas_kernels.h
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: PR/READY2MERGE

#2792 [trivial] remove unused function (initialize func of layer)
  api/ccapi/include/layer.h
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_node.h
Labels: PR/READY2MERGE

#2798 [ golden ] OpenCl Transpose layer golden is added.
  packaging/unittest_layers.tar.gz
Labels: PR/READY2MERGE

#2799 [Tensor] Support Read/Save Functionalities for Quantized Type
  nntrainer/tensor/char_tensor.cpp
  nntrainer/tensor/char_tensor.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor_base.h
Labels: PR/READY2MERGE

#2759 [GPU/OpenCL] Broadcasting support added for GPU Addition kernel.
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/addition_layer_cl.cpp
  nntrainer/layers/cl_layers/addition_layer_cl.h
  nntrainer/layers/cl_layers/meson.build
  nntrainer/tensor/cl_operations/blas_kernel_interface.cpp
  nntrainer/tensor/cl_operations/blas_kernel_interface.h
  nntrainer/tensor/cl_operations/blas_kernel_strings.h
  nntrainer/tensor/cl_operations/blas_kernels.cpp
  nntrainer/tensor/cl_operations/blas_kernels.h
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
  test/include/nntrainer_test_util.h
  test/jni/Android.mk
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: PR/READY2MERGE

#2794 [Graph] change of inplace-type setting method
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/flatten_layer.h
  nntrainer/layers/identity_layer.h
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/multiout_layer.h
  nntrainer/layers/reshape_layer.h
Labels: PR/READY2MERGE

#2795 [Graph] rename variable and remove non-working codes @open sesame 11/14 19:02
  nntrainer/layers/acti_func.h
  nntrainer/layers/input_layer.cpp
  nntrainer/layers/input_layer.h
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/loss/loss_layer.cpp
  nntrainer/layers/loss/loss_layer.h
Labels: PR/READY2MERGE

#2803 [Bugfix] Revert mixed precision case inplace set false
  nntrainer/layers/input_layer.cpp
  nntrainer/layers/input_layer.h
  nntrainer/layers/loss/loss_layer.cpp
  nntrainer/layers/loss/loss_layer.h
Labels: Need Review

#2805 [Trivial] Change Android Log type
  nntrainer/models/neuralnet.cpp
Labels: Need Review

#2800 [trivial] bug fix on recorder_v2.py script
  test/input_gen/genModelTests_v2.py
  test/input_gen/recorder_v2.py
Labels: PR/READY2MERGE

#2807 [CI] Drop i586 GBS build test
  .github/workflows/gbs_build.yml
Labels: Need Review
