Repository nnstreamer/nntrainer, pull requests merged in 2025-05, with the labels that each got.

#3140 [Windows] Add getting started guide
  docs/getting-started-windows.md
  docs/getting-started.md
Labels: PR/READY2MERGE

#3152 [Fix] Fix copy data unit tests
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#3119 [OpenCL] Fix Half-Precision Kernels
  nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
Labels: PR/READY2MERGE

#3129 [Test] Refactor OpenCL BLAS kernel tests
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: PR/READY2MERGE

#3157 [CI] Add clang build to continues integration
  .github/workflows/ubuntu_clean_meson_build_clang.yml
  linux-native-clang.ini
  nntrainer/engine.h
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: PR/READY2MERGE

#3144 [Performance] Avoid using shared_ptr.
  nntrainer/tensor/bcq_tensor.cpp
  nntrainer/tensor/bcq_tensor.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_base.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#3153 [x86_64] AVX approximation of swiglu
  meson.build
  nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
  nntrainer/tensor/cpu_backend/x86/avx2_impl.h
  nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
Labels: PR/READY2MERGE

#3146 Bugfix: GGML Build Error in NNTrainer on Ubuntu 20.04
  meson.build
Labels: Need Review

#3132 [Tensor] Add Q4_K Tensor class @open sesame (2025-05-08 15:17)
  debian/nntrainer-dev.install
  nntrainer/tensor/meson.build
  nntrainer/tensor/q4_k_tensor.cpp
  nntrainer/tensor/q4_k_tensor.h
  nntrainer/tensor/quantizer.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/uint4_tensor.h
  packaging/nntrainer.spec
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: Need Review

#3177 [Wait for #3132, #3176] Q4_K Weight
  api/ccapi/include/tensor_dim.h
  nntrainer/layers/layer_context.h
  nntrainer/models/model_common_properties.h
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/q4_k_tensor.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor_dim.cpp
  nntrainer/tensor/uint4_tensor.h
  nntrainer/utils/base_properties.h
  test/unittest/unittest_nntrainer_graph.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: Need Review

#3169 [onnx] add new directory and readme for onnx converter
  subprojects/ONNXConverter/README.md
Labels: Need Review

#3122 [OpenCL] Optimized Single-Precision GEMM Kernel
  nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
  nntrainer/tensor/cl_operations/blas_kernels.cpp
Labels: Need Review

#3175 [FSU] Bugfix on FSU-OFF & Look_ahead Given Case
  nntrainer/models/neuralnet.cpp
Labels: PRIORITY/HIGH, Need Review

#3139 [FSU][Unittest] Add FSU Unittest
  nntrainer/tensor/cache_elem.cpp
  test/unittest/integration_tests/integration_test_fsu.cpp
  test/unittest/integration_tests/meson.build
Labels: Need Review

#3182 [Windows support] Remove openblas patch
  subprojects/openblas.wrap
  subprojects/packagefiles/openblas/0001-Aid-windows-cross-compile-wine-MSVC.patch
Labels: Need Review

#3161 [Fix] Fix major warnings found by clang
  nntrainer/layers/layer_node.cpp
  nntrainer/mem_allocator.cpp
  nntrainer/models/model_loader.h
  nntrainer/optimizers/optimizer_wrapped.cpp
  nntrainer/tensor/bcq_tensor.h
  nntrainer/tensor/swap_device.h
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_pool.cpp
  nntrainer/tensor/uint4_tensor.cpp
  nntrainer/utils/util_func.cpp
Labels: PR/READY2MERGE

#3187 [ q4K ] Enable non-4-divisible-M q4K GEMM case
  nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
  test/unittest/unittest_nntrainer_cpu_backend.cpp
Labels: Need Review

#3192 [Git] Update git ignored
  .gitignore
Labels: PR/READY2MERGE

#3190 [Bugfix] Bugs in BCQTensor are fixed
  nntrainer/tensor/bcq_tensor.cpp
Labels: PR/READY2MERGE

#3123 [OpenCL] Optimized Half-Precision GEMM Kernel @open sesame 05/22 09:09
  nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
Labels: PR/READY2MERGE

#3195 [Windows] Fix OpenMP linking problem of ggml on windows clang build
  jni/prepare_ggml.sh
  meson.build
  subprojects/ggml.wrap
  subprojects/packagefiles/ggml/0001-nntrainer-ggml-patch.patch
Labels: PR/READY2MERGE

#3191 [Props] add WeightDType property
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/utils/base_properties.h
  nntrainer/utils/node_exporter.cpp
  nntrainer/utils/node_exporter.h
  test/unittest/layers/unittest_layer_node.cpp
Labels: Need Review
