Repository nnstreamer/nntrainer, pull requests merged in 2025-08, with the labels that each got.

#3382 [unittest] add negative unittests
  test/unittest/layers/unittest_layer_node.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
Labels: PR/READY2MERGE

#3395 [bugfix] remove unused header
  test/unittest/integration_tests/integration_test_loss.cpp
Labels: Need Review

#3299 Replace repeating FP16/FP32 code with template
  nntrainer/opencl/opencl_kernel.cpp
  nntrainer/tensor/cl_operations/blas_kernels.cpp
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
  nntrainer/tensor/cl_operations/blas_kernels_templates.h
Labels: PR/READY2MERGE

#3305 Remove repeating code in attention kernels
  nntrainer/tensor/cl_operations/attention_kernels.cpp
  nntrainer/tensor/cl_operations/attention_kernels.h
  nntrainer/tensor/cl_operations/attention_kernels_fp16.cpp
  nntrainer/tensor/cl_operations/attention_kernels_templates.h
Labels: PR/READY2MERGE

#3329 build/install: install path of nnstreamer subplugins
  meson_options.txt
  nnstreamer/tensor_filter/meson.build
  nnstreamer/tensor_trainer/meson.build
  packaging/nntrainer.spec
Labels: Need Review, Stale

#3348 [Tensor] Implement Q4_0 Tensor
  api/ccapi/include/tensor_dim.h
  debian/nntrainer-dev.install
  nntrainer/tensor/meson.build
  nntrainer/tensor/q4_0_tensor.cpp
  nntrainer/tensor/q4_0_tensor.h
  nntrainer/tensor/quantizer.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor_dim.cpp
  packaging/nntrainer.spec
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: Need Review

#3353 [Q6_K] Update Q6_K dot opration.
  nntrainer/tensor/float_tensor.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: Need Review

#3366 Wrap nntrainer::ErrorNotification with warning suppressor
  nntrainer/nntrainer_error.h
Labels: Need Review

#3369 [OpenCL] Load clWaitForEvents
  nntrainer/opencl/opencl_loader.cpp
  nntrainer/opencl/opencl_loader.h
Labels: Need Review

#3388 [Docs] Updated the guide for Android
  docs/how-to-run-example-android.md
Labels: Need Review

#3421 [Bugfix] neuralnet load is fixed.
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2MERGE
