Repository nnstreamer/nntrainer, pull requests merged in 2025-09, with the labels that each got.

#3443 [OpenCL] Asynchronous Execution and Out-of-Order Queue Support
  nntrainer/cl_buffer_manager.cpp
  nntrainer/cl_buffer_manager.h
  nntrainer/opencl/opencl_command_queue_manager.cpp
  nntrainer/tensor/cl_operations/blas_kernels.cpp
  nntrainer/tensor/cl_operations/blas_kernels.h
  nntrainer/tensor/float_tensor.cpp
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: Need Review

#3439 Add timer
  test/include/timer.h
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: PR/READY2MERGE

#3482 [ CausalLM ] enable kv cache save / load
  Applications/CausalLM/causal_lm.cpp
  Applications/CausalLM/causal_lm.h
  Applications/CausalLM/layers/embedding_layer.cpp
  Applications/CausalLM/layers/mha_core.cpp
  Applications/CausalLM/layers/mha_core.h
  Applications/CausalLM/layers/qwen_moe_layer.cpp
  Applications/CausalLM/layers/qwen_moe_layer_cached.cpp
  Applications/CausalLM/layers/qwen_moe_layer_fsu.cpp
  Applications/CausalLM/layers/reshaped_rms_norm.cpp
  Applications/CausalLM/layers/rms_norm.cpp
  Applications/CausalLM/layers/tie_word_embedding.cpp
  Applications/LLaMA/jni/swiglu.cpp
  nntrainer/layers/addition_layer.cpp
  nntrainer/layers/fc_layer.cpp
  nntrainer/models/neuralnet.cpp
Labels: Need Review

#3475 [git] update ignore file to exclude res/*
  .gitignore
Labels: Need Review

#3476 [CausalLM] enable Q4_0 in Embedding Layer
  Applications/CausalLM/layers/embedding_layer.cpp
Labels: PR/READY2MERGE

#3453 Cache built kernel binaries and load them on subsequent runs
  nntrainer/cl_context.cpp
  nntrainer/opencl/opencl_program.cpp
  nntrainer/opencl/opencl_program.h
Labels: Need Review

#3477 Restricting OpenCL Context Usage When Unavailable
  nntrainer/cl_context.cpp
  nntrainer/cl_context.h
  nntrainer/opencl/opencl_buffer.cpp
  nntrainer/opencl/opencl_command_queue_manager.cpp
  nntrainer/opencl/opencl_context_manager.cpp
  nntrainer/opencl/opencl_loader.cpp
Labels: Need Review

#3488 Fix build after merge due to not renamed kernel name
  nntrainer/tensor/cl_operations/blas_kernels.cpp
Labels: Need Review

#3494 Fix: Tail Handling Bug in SwiGLU AVX2 Kernel
  nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
Labels: Need Review, bugfix

#3478 [CausalLM] updeate gpt-moe-cached to support MM
  Applications/CausalLM/layers/gpt_oss_moe_layer_cached.cpp
Labels: PR/READY2MERGE

#3513 [ ruy ] Set ruy usage to false by default
  debian/control
  debian/rules
  debian/ruy.install
  jni/Android.mk.in
  jni/meson.build
  meson_options.txt
  packaging/nntrainer.spec
  test/jni/Android.mk
Labels: PR/READY2MERGE
