Repository nnstreamer/nntrainer, pull requests merged in 2025-07, with the labels that each got.

#3278 memory leak fix (valgrind error): unit test tizen capi optimizer
  test/tizen_capi/unittest_tizen_capi_optimizer.cpp
Labels: PR/READY2MERGE

#3221 [model] update time step
  api/ccapi/include/model.h
  nntrainer/graph/network_graph.cpp
  nntrainer/graph/network_graph.h
  nntrainer/layers/addition_layer.cpp
  nntrainer/layers/addition_layer.h
  nntrainer/layers/input_layer.cpp
  nntrainer/layers/input_layer.h
  nntrainer/layers/layer_context.cpp
  nntrainer/layers/layer_context.h
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/multiout_layer.cpp
  nntrainer/layers/multiout_layer.h
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/var_grad.h
Labels: PR/READY2MERGE

#3279 memory leak fix (valgrind error): int4_tensor leak
  nntrainer/tensor/int4_tensor.cpp
Labels: PR/READY2MERGE

#3277 memory leak fix (valgrind error): engine and context
  nntrainer/engine.cpp
  nntrainer/engine.h
Labels: PR/READY2MERGE

#3287 [Docs] simple update to improve readability
  nntrainer/tensor/cpu_backend/README.md
Labels: Need Review

#3280 memory leak fix (valgrind error): layer unittest
  test/unittest/layers/unittest_layer_node.cpp
Labels: PR/READY2MERGE

#3290 readme: update supported ubuntu version.
  README.md
Labels: PR/READY2MERGE

#3284 [Fix] Fix nan values problem while beta calculation.
  nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
  nntrainer/tensor/cpu_backend/fallback/fallback_internal_fp16.cpp
  nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor_base.h
  test/unittest/models/models_test_utils.cpp
Labels: PR/READY2MERGE

#3286 Add OpenCL Intel GPU selection
  nntrainer/opencl/opencl_context_manager.cpp
Labels: PR/READY2MERGE, GPU

#3281 memory leak fix (valgrind error): Application/KNN
  Applications/KNN/jni/main.cpp
Labels: PR/READY2MERGE

#3363 [OpenCL] Add Compiler Flags for Optimization
  nntrainer/opencl/opencl_program.cpp
Labels: PR/READY2MERGE

#3346 Remove unused file
  nntrainer/delegate.h
Labels: Need Review

#3321 Lets make singletons great again.
  Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp
  Applications/Custom/LayerPlugin/layer_plugin_common_test.h
  Applications/Custom/OptimizerPlugin/optimizer_plugin_common_test.cpp
  Applications/Custom/OptimizerPlugin/optimizer_plugin_common_test.h
  generate_def.py
  nntrainer/app_context.cpp
  nntrainer/app_context.h
  nntrainer/cl_buffer_manager.cpp
  nntrainer/cl_buffer_manager.h
  nntrainer/cl_context.cpp
  nntrainer/cl_context.h
  nntrainer/context.h
  nntrainer/engine.cpp
  nntrainer/engine.h
  nntrainer/layers/cl_layers/addition_layer_cl.h
  nntrainer/layers/cl_layers/concat_cl.cpp
  nntrainer/layers/cl_layers/concat_cl.h
  nntrainer/layers/cl_layers/fc_layer_cl.h
  nntrainer/layers/cl_layers/layer_impl_cl.h
  nntrainer/layers/cl_layers/reshape_cl.cpp
  nntrainer/layers/cl_layers/reshape_cl.h
  nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
  nntrainer/layers/cl_layers/rmsnorm_layer_cl.h
  nntrainer/layers/cl_layers/swiglu_cl.cpp
  nntrainer/layers/cl_layers/swiglu_cl.h
  nntrainer/layers/cl_layers/transpose_cl.h
  nntrainer/meson.build
  nntrainer/models/dynamic_training_optimization.cpp
  nntrainer/models/dynamic_training_optimization.h
  nntrainer/nntrainer_logger.cpp
  nntrainer/opencl/opencl_buffer.h
  nntrainer/opencl/opencl_command_queue_manager.cpp
  nntrainer/opencl/opencl_command_queue_manager.h
  nntrainer/opencl/opencl_context_manager.cpp
  nntrainer/opencl/opencl_context_manager.h
  nntrainer/opencl/opencl_op_interface.h
  nntrainer/tensor/cl_operations/attention_kernels.cpp
  nntrainer/tensor/cl_operations/attention_kernels.h
  nntrainer/tensor/cl_operations/attention_kernels_fp16.cpp
  nntrainer/tensor/cl_operations/blas_kernels.cpp
  nntrainer/tensor/cl_operations/blas_kernels.h
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
  nntrainer/tensor/cl_operations/clblast_interface.cpp
  nntrainer/tensor/cl_operations/clblast_interface.h
  nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface_bs_threadpool.cpp
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/manager.h
  nntrainer/tensor/memory_pool.cpp
  nntrainer/tensor/memory_pool.h
  nntrainer/utils/bs_thread_pool_manager.cpp
  nntrainer/utils/bs_thread_pool_manager.hpp
  nntrainer/utils/noncopyable.h
  nntrainer/utils/nonmovable.h
  nntrainer/utils/profiler.cpp
  nntrainer/utils/profiler.h
  nntrainer/utils/singleton.h
Labels: PR/READY2MERGE

#3380 [Tensor] Remove SVM Allocation
  nntrainer/tensor/float_tensor.cpp
Labels: Need Review
