Repository nnstreamer/nntrainer, pull requests merged in 2025-02, with the labels that each got.

#2884 [Windows] Avoid using dirent.h
  nntrainer/app_context.cpp
Labels: rebase required, PR/READY2MERGE

#2903 tizen spec: fix path macros
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#2896 Fix opencl/context member property init.
  nntrainer/opencl/opencl_context_manager.cpp
Labels: PR/READY2MERGE

#2902 meson: avx condition fix.
  meson.build
  nntrainer/tensor/meson.build
Labels: PR/READY2MERGE

#2910 blas_interface.cpp: header syntax fix
  nntrainer/tensor/blas_interface.cpp
Labels: PR/READY2MERGE

#2907 [TensorPool] Memory allocation for quantized tensor scale factors
  nntrainer/tensor/tensor_pool.cpp
  test/unittest/unittest_nntrainer_tensor_pool.cpp
Labels: PR/READY2MERGE

#2913 [Coverity] Fix double_unlock issue in markFilled()
  nntrainer/dataset/iteration_queue.cpp
Labels: Need Review

#2919 [Coverity] Fix Coverity issue at neuralnet destructor
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2MERGE

#2925 Memory Leak Fixes in NNTrainer
  nntrainer/tensor/char_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/short_tensor.cpp
  nntrainer/tensor/uint_tensor.cpp
Labels: Need Review

#2904 Compile nntrainer on windows
  meson.build
  meson_options.txt
  nntrainer/app_context.cpp
  nntrainer/compiler/remap_realizer.h
  nntrainer/dataset/databuffer.cpp
  nntrainer/dataset/dir_data_producers.cpp
  nntrainer/layers/acti_func.h
  nntrainer/layers/dropout.h
  nntrainer/layers/rnn.cpp
  nntrainer/layers/rnncell.cpp
  nntrainer/models/dynamic_training_optimization.cpp
  nntrainer/nntrainer_log.h
  nntrainer/nntrainer_logger.cpp
  nntrainer/optimizers/lr_scheduler_cosine.cpp
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/manager.cpp
  nntrainer/tensor/manager.h
  nntrainer/tensor/swap_device.cpp
  nntrainer/tensor/swap_device.h
  nntrainer/tensor/task_executor.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/weight.h
Labels: PR/READY2MERGE

#2911 [ coverity ] Fix coverity issue : leaked_storage
  nntrainer/app_context.cpp
Labels: PR/READY2MERGE

#2912 [Coverity] Fix DIVIDE_BY_ZERO issue
  nntrainer/layers/preprocess_l2norm_layer.cpp
  nntrainer/layers/preprocess_l2norm_layer.h
Labels: PR/READY2MERGE

#2929 [docs] update meson version document
  docs/getting-started.md
  docs/how-to-run-examples.md
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#2928 [Coverity] Fix Coverity issue on ini_interpreter (path nullptr excetion)
  nntrainer/compiler/ini_interpreter.cpp
Labels: Need Review

#2923 [Coverity] resolve coverity issues
  nntrainer/app_context.cpp
  nntrainer/models/neuralnet.cpp
  nntrainer/tensor/memory_data.h
Labels: Need Review

#2918 [Coverity] Fix Coverity issue at KNN Application
  Applications/KNN/jni/main.cpp
Labels: PR/READY2MERGE

#2881 [ neon ] Implement neon kernel for copy_s16_f32
  nntrainer/tensor/blas_interface.cpp
  nntrainer/tensor/blas_neon.cpp
Labels: PR/READY2MERGE

#2891 [ONNX] add onnx proto & meson setting
  meson_options.txt
  nntrainer/compiler/meson.build
  nntrainer/compiler/onnx.proto
Labels: PR/READY2MERGE

#2898 [ matrix_transpose ] Divide f16 transpose and f32 transpose with NEON
  nntrainer/tensor/blas_interface.cpp
  nntrainer/tensor/matrix_transpose_neon/matrix_transpose_neon.cpp
  nntrainer/tensor/matrix_transpose_neon/matrix_transpose_neon_f16.cpp
  nntrainer/tensor/matrix_transpose_neon/meson.build
  nntrainer/tensor/meson.build
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#2895 [Tensor] Int4QTensor with quantized 4-bit integer data type
  debian/nntrainer-dev.install
  nntrainer/tensor/int4_tensor.cpp
  nntrainer/tensor/int4_tensor.h
  nntrainer/tensor/meson.build
  nntrainer/tensor/tensor.cpp
  packaging/nntrainer.spec
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#2931 [bugfix] Unsupported option errors in Android build
  test/jni/Android.mk
  test/unittest/jni/Android.mk
Labels: Need Review

#2914 [Coverity] Wrap main() with try-catch block (#1839950)
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Labels: PR/READY2MERGE

#2915 [Coverity] Wrap main() with try-catch block (#1840519)
  Applications/SimpleShot/task_runner.cpp
Labels: PR/READY2MERGE

#2916 [Coverity] Wrap main() with try-catch block (#1840581)
  Applications/ReinforcementLearning/DeepQ/jni/main.cpp
Labels: PR/READY2MERGE

#2933 [Bug] fix memory leakage issue in inference mode @open sesame 02/10 19:43
  nntrainer/tensor/memory_pool.cpp
Labels: PR/READY2MERGE

#2926 [coverity] resolve exception handle issue @open sesame 02/08 11:04
  Applications/TransferLearning/CIFAR_Classification/jni/main.cpp
  api/ccapi/include/layer.h
  nntrainer/graph/graph_node.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/nntrainer_logger.cpp
Labels: PR/READY2MERGE

#2920 [ coverity ] Fix coverity issue : Double unlocking @open sesame 02/08 11:00
  nntrainer/tensor/task_executor.cpp
Labels: BUILD/CI, PR/READY2MERGE

#2932 [Tensor] Scale factors support for unsigned int type
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/uint_tensor.cpp
  nntrainer/tensor/uint_tensor.h
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE, PR/OK2GO

#2921 [Log] Change the log files to be saved under the logs folder
  nntrainer/nntrainer_logger.cpp
  nntrainer/nntrainer_logger.h
Labels: PR/READY2MERGE

#2946 [Coverity] Fix Coverity issue
  nntrainer/tensor/short_tensor.cpp
Labels: Need Review

#2942 [ Doc ] add a note about the gcc/g++ version (enable_fp16)
  docs/getting-started.md
  docs/how-to-run-examples.md
Labels: Need Review

#2934 [ Doc ] Add install submodule step to `getting-sarted.md`
  docs/getting-started.md
Labels: Need Review

#2947 [trivial] add header files @open sesame 02/13 17:20
  Applications/Multi_input/jni/multi_loader.cpp
  Applications/YOLOv3/jni/det_dataloader.cpp
  nntrainer/utils/util_simd.cpp
Labels: Need Review

#2944 [coverity] fix un-initialization issues
  nntrainer/graph/network_graph.h
  nntrainer/layers/layer_node.cpp
  nntrainer/tensor/char_tensor.cpp
  nntrainer/tensor/char_tensor.h
  nntrainer/tensor/int4_tensor.cpp
  nntrainer/tensor/int4_tensor.h
  nntrainer/tensor/quantizer.h
  nntrainer/tensor/short_tensor.h
  nntrainer/tensor/uint_tensor.h
Labels: Need Review

#2950 [windows] replace strerror with thread_safe func
  Applications/utils/datagen/cifar/cifar_dataloader.cpp
  benchmarks/fake_data_gen/fake_data_gen.cpp
  nntrainer/compiler/tflite_interpreter.cpp
  nntrainer/models/model_loader.cpp
  nntrainer/nntrainer_error.h
  nntrainer/tensor/swap_device.cpp
  nntrainer/utils/ini_wrapper.cpp
  nntrainer/utils/util_func.h
  test/ccapi/unittest_ccapi.cpp
  test/unittest/compiler/unittest_interpreter.cpp
  test/unittest/compiler/unittest_tflite_export.cpp
  test/unittest/models/models_golden_test.cpp
Labels: PR/READY2MERGE

#2941 [UnitTest] Update Integration_test_fsu
  test/unittest/integration_tests/integration_test_fsu.cpp
Labels: PR/READY2MERGE

#2939 [CI] update Github-hosted runner & remove Ubuntu 20.04 @open sesame 02/12 13:01
  .github/workflows/daily_build.yml
  .github/workflows/pdebuild.yml
  .github/workflows/ubuntu_benchmarks.yml
  .github/workflows/ubuntu_clean_meson_build.yml
Labels: PR/READY2MERGE

#2924 [Windows] Modify meson build to support windows
  meson.build
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/reshape_cl.cpp
  nntrainer/meson.build
  nntrainer/opencl/opencl_program.cpp
  windows-native.ini
Labels: PR/READY2MERGE

#2940 [Tensor] Zero point support for unsigned int type 
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_base.h
  nntrainer/tensor/tensor_pool.cpp
  nntrainer/tensor/uint_tensor.cpp
  nntrainer/tensor/uint_tensor.h
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE, PR/OK2GO

#2850 [CharTensor] Enable QINT8 multiplication feature
  nntrainer/tensor/char_tensor.cpp
  nntrainer/tensor/char_tensor.h
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#2908 [Util] Floating-point and fixed-point conversion
  nntrainer/utils/util_func.cpp
  nntrainer/utils/util_func.h
Labels: PR/READY2MERGE

#2960 [coverity] fix coverity & svace issues
  Applications/ProductRatings/jni/main.cpp
  Applications/TransferLearning/CIFAR_Classification/jni/main.cpp
  nntrainer/tensor/manager.h
  nntrainer/tensor/quantizer.h
  nntrainer/tensor/uint_tensor.h
Labels: PR/READY2MERGE
