Repository nnstreamer/nntrainer, pull requests merged in 2025-06, with the labels that each got.

#3220 [Q6K] clarify `override` for parent's pure virtual
  nntrainer/tensor/q6_k_tensor.h
Labels: PR/READY2MERGE

#3224 [Template] Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR/READY2MERGE

#3227 [LoRA] bugfix in LoRA
  nntrainer/layers/fc_layer.cpp
Labels: Need Review

#3233 Do not split qantization and dot steps
  nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
Labels: PR/READY2MERGE

#3232 [Quality] Fix all warnings reported by clang
  Applications/Custom/OptimizerPlugin/optimizer_plugin_common_test.h
  Applications/Custom/mae_loss.h
  Applications/Custom/momentum.h
  Applications/Custom/rnnt_loss.h
  Applications/Multi_input/jni/multi_loader.cpp
  Applications/YOLOv2/jni/yolo_v2_loss.h
  Applications/YOLOv3/jni/yolo_v3_loss.h
  Applications/utils/datagen/cifar/cifar_dataloader.cpp
  Applications/utils/datagen/cifar/cifar_dataloader.h
  linux-native-clang.ini
  meson.build
  nntrainer/compiler/tflite_interpreter.cpp
  nntrainer/dataset/random_data_producers.cpp
  nntrainer/graph/graph_core.h
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/models/neuralnet.cpp
  nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
  nntrainer/tensor/memory_pool.h
  nntrainer/tensor/quantizer.h
  nntrainer/utils/util_func.cpp
  test/nntrainer_test_util.cpp
  test/unittest/layers/layers_common_tests.h
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_positional_encoding.cpp
  test/unittest/memory/meson.build
  test/unittest/memory/unittest_memory_planner.cpp
  test/unittest/unittest_base_properties.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: Need Review

#3201 [Test] Disable DefaultEnvironmentPath Test
  Applications/Custom/LayerPlugin/layer_plugin_common_test.cpp
  Applications/Custom/LayerPlugin/layer_plugin_test.cpp
  Applications/Custom/OptimizerPlugin/optimizer_plugin_common_test.cpp
  test/unittest/layers/layers_standalone_common_tests.cpp
Labels: PR/READY2MERGE

#3213 Add getProperty function
  api/ccapi/include/layer.h
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_impl.cpp
  nntrainer/layers/layer_impl.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/utils/util_func.h
Labels: PR/READY2MERGE

#3203 Bugfix: OpenCL HGEMM kernel for TransA
  nntrainer/opencl/opencl_buffer.cpp
  nntrainer/tensor/cl_operations/blas_kernel_strings.cpp
Labels: PR/READY2MERGE, GPU

#3214 [App] Update weight conversion script to support lora
  Applications/LLaMA/PyTorch/weights_converter.py
Labels: Need Review

#3243 Add AVX implementation of ele_mul() and ele_add().
  nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
  nntrainer/tensor/cpu_backend/x86/avx2_impl.h
  nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
  test/unittest/unittest_nntrainer_cpu_backend.cpp
Labels: Need Review

#3241 Remove leftover unused function
  nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
Labels: PR/READY2MERGE

#3260 [Fix] Fix memory access violation in fp16
  nntrainer/tensor/cpu_backend/x86/avx2_impl_fp16.cpp
Labels: PR/READY2MERGE

#3222 [Fix] Fix ggml assertion in q6K quantization test
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE, UnitTest

#3272 contributing: update the committers.
  CONTRIBUTING.md
Labels: Need Review

#3242 Rework of Q6 GEMM
  nntrainer/tensor/cpu_backend/ggml_interface/ggml_interface.cpp
Labels: PR/READY2MERGE
