Repository nnstreamer/nntrainer, pull requests merged in 2025-01, with the labels that each got.

#2834 [Blas] copy functionality for signed int8 data type
  nntrainer/tensor/blas_interface.cpp
  nntrainer/tensor/blas_interface.h
  nntrainer/tensor/blas_neon.cpp
  nntrainer/tensor/blas_neon.h
  nntrainer/tensor/char_tensor.cpp
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/half_tensor.cpp
Labels: Need Review

#2835 [Unittest] FSU Unittest with Simple FC Model
  test/unittest/integration_tests/integration_test_fsu.cpp
  test/unittest/integration_tests/meson.build
Labels: PR/READY2MERGE

#2833 [ meson ] remove hard code path in meson script @open sesame 12/23 15:55
  meson.build
  meson_options.txt
  nntrainer/tensor/meson.build
Labels: PR/READY2MERGE

#2849 Add ComputeEngine Property for choosing Engine
  api/ccapi/include/common.h
  api/ccapi/include/layer.h
  api/ccapi/src/factory.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/utils/node_exporter.cpp
  nntrainer/utils/node_exporter.h
  test/unittest/layers/layers_dependent_common_tests.cpp
Labels: PR/READY2MERGE

#2852 [FSU][Bugfix] Bugfix on FSU Inference
  nntrainer/tensor/manager.cpp
Labels: bug, Need Review

#2797 [Wait for #2796][Graph] add inplace direction setting through layer property
  nntrainer/graph/network_graph.cpp
  nntrainer/layers/add_layer.h
  nntrainer/layers/common_properties.h
  nntrainer/layers/divide_layer.h
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/layer_node.h
  nntrainer/layers/multiply_layer.h
  nntrainer/layers/subtract_layer.h
  nntrainer/utils/node_exporter.h
Labels: PR/READY2MERGE

#2828 [Quantizer] PerTensorAffineQuantizer operations
  nntrainer/tensor/quantizer.cpp
  nntrainer/tensor/quantizer.h
  test/unittest/meson.build
  test/unittest/unittest_nntrainer_quantizer.cpp
Labels: PR/READY2MERGE

#2853 [ Init ] Verify optimizer during initialization according to execution mode.
  nntrainer/models/neuralnet.cpp
  test/ccapi/unittest_ccapi.cpp
  test/tizen_capi/unittest_tizen_capi.cpp
  test/unittest/compiler/unittest_tflite_export.cpp
  test/unittest/unittest_nntrainer_exe_order.cpp
  test/unittest/unittest_nntrainer_graph.cpp
Labels: PR/READY2MERGE

#2844 [CharTensor] Enable memory data to store scale factors based on quantization schemes
  nntrainer/tensor/char_tensor.cpp
  nntrainer/tensor/char_tensor.h
  nntrainer/tensor/quantizer.cpp
  nntrainer/tensor/quantizer.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_base.h
  test/unittest/unittest_nntrainer_quantizer.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: Need Review

#2873 [ trivial ] Add reviewers
  README.md
Labels: PR/READY2MERGE

#2866 [Tensor] ShortTensor class with quantized signed 16-bit integer
  api/ccapi/include/tensor_dim.h
  debian/nntrainer-dev.install
  nntrainer/tensor/meson.build
  nntrainer/tensor/short_tensor.cpp
  nntrainer/tensor/short_tensor.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_dim.cpp
  nntrainer/utils/base_properties.h
  packaging/nntrainer.spec
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#2872 [ graph ] Divide addLossLayer process when compiling inference model graph @open sesame 01/15 14:27
  api/ccapi/include/model.h
  nntrainer/graph/network_graph.cpp
  nntrainer/models/neuralnet.cpp
  nntrainer/models/neuralnet.h
  test/unittest/integration_tests/integration_test_fsu.cpp
  test/unittest/unittest_nntrainer_graph.cpp
Labels: PR/READY2MERGE

#2871 [trivial] Update CODEOWNERS
  .github/CODEOWNERS
Labels: PR/READY2MERGE

#2880 Update: New URL for NNStreamer Latest Android Build
  jni/prepare_ml-api.sh
Labels: bug, PR/READY2MERGE

#2875 [CI] Add daily Ubuntu build
  .github/workflows/daily_build.yml
Labels: PR/READY2MERGE

#2876 [Blas] copy functionality for signed int16 data type
  nntrainer/tensor/blas_interface.cpp
  nntrainer/tensor/blas_interface.h
  nntrainer/tensor/blas_neon.cpp
  nntrainer/tensor/blas_neon.h
  nntrainer/tensor/float_tensor.cpp
Labels: PR/READY2MERGE

#2878 [CI] update static checker script to downgrade clang-format version.
  .github/workflows/cpp_linter.yml
  .github/workflows/static.check.yml
Labels: PR/READY2MERGE

#2882 Update: NNstreamer-lite-Native URL with const name
  jni/prepare_ml-api.sh
Labels: PR/READY2MERGE

#2874 Enhanced Quantizer with QINT16 Support
  nntrainer/tensor/quantizer.cpp
  nntrainer/tensor/quantizer.h
  test/unittest/unittest_nntrainer_quantizer.cpp
Labels: PR/READY2MERGE

#2870 [Windows] Use portable version of strerror
  Applications/utils/datagen/cifar/cifar_dataloader.cpp
  benchmarks/fake_data_gen/fake_data_gen.cpp
  nntrainer/compiler/tflite_interpreter.cpp
  nntrainer/models/model_loader.cpp
  nntrainer/tensor/swap_device.cpp
  nntrainer/utils/ini_wrapper.cpp
  nntrainer/utils/util_func.h
  test/ccapi/unittest_ccapi.cpp
  test/unittest/compiler/unittest_interpreter.cpp
  test/unittest/compiler/unittest_tflite_export.cpp
  test/unittest/models/models_golden_test.cpp
Labels: PR/READY2MERGE, PR/OK2GO

#2809 [ GPU ] split kernel register from forwarding function in `swiglu_cl` @open sesame 12/02 10:40
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/swiglu_cl.cpp
  nntrainer/layers/cl_layers/swiglu_cl.h
Labels: PR/READY2MERGE

#2810 [ GPU ] split kernel registration from forwarding function in `addition_layer_cl` and `transpose_cl`
  nntrainer/cl_context.cpp
  nntrainer/layers/cl_layers/addition_layer_cl.h
  nntrainer/layers/cl_layers/transpose_cl.h
Labels: PR/READY2MERGE

#2863 [GPU] Added multiple fp16 unittests for blas kernel operations.
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: PR/READY2MERGE, UnitTest

#2879 [Windows] Add multi os wrapper for loading dynamic libraries
  Applications/Custom/LayerPlugin/layer_plugin_test.cpp
  debian/nntrainer-dev.install
  nntrainer/app_context.cpp
  nntrainer/opencl/opencl_loader.cpp
  nntrainer/utils/dynamic_library_loader.h
  nntrainer/utils/meson.build
  packaging/nntrainer.spec
Labels: rebase required, PR/READY2MERGE

#2890 [Windows] Replace uint with unsigned int @open sesame 01/22 16:36
  Applications/Android/NNDetector/app/src/main/jni/dataloader.cpp
  Applications/Android/NNDetector/app/src/main/jni/dataloader.h
  Applications/Android/NNDetector/app/src/main/jni/simpleshot.cpp
  Applications/Android/PicoGPTJNI/app/src/main/jni/picogpt.cpp
  Applications/Android/ResnetJNI/app/src/main/jni/dataloader.cpp
  Applications/Android/ResnetJNI/app/src/main/jni/dataloader.h
  Applications/PicoGPT/jni/main.cpp
  Applications/ProductRatings/jni/main.cpp
  Applications/SimpleFC/jni/main.cpp
  Applications/YOLOv2/jni/det_dataloader.cpp
  Applications/YOLOv3/jni/det_dataloader.cpp
  api/capi/include/nntrainer_internal.h
  api/ccapi/include/tensor_dim.h
  nntrainer/dataset/dir_data_producers.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/embedding.cpp
  nntrainer/layers/layer_node.cpp
  nntrainer/layers/preprocess_l2norm_layer.cpp
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_dim.cpp
  test/unittest/integration_tests/integration_test_fsu.cpp
Labels: PR/READY2MERGE

#2801 [layer] add pow operation layer @open sesame 12/06 20:13
  Applications/Custom/LayerClient/jni/main.cpp
  Applications/Custom/LayerClient/res/custom_layer_client.ini
  Applications/Custom/LayerPlugin/layer_plugin_pow_test.cpp
  Applications/Custom/LayerPlugin/layer_plugin_test.cpp
  Applications/Custom/pow.h
  api/ccapi/include/layer.h
  api/nntrainer-api-common.h
  nntrainer/app_context.cpp
  nntrainer/layers/common_properties.cpp
  nntrainer/layers/common_properties.h
  nntrainer/layers/meson.build
  nntrainer/layers/pow_layer.cpp
  nntrainer/layers/pow_layer.h
  nntrainer/utils/node_exporter.h
  packaging/unittest_models_v2.tar.gz
  test/input_gen/genModelTests_v2.py
  test/unittest/layers/meson.build
  test/unittest/layers/unittest_layers_pow.cpp
  test/unittest/models/unittest_models.cpp
Labels: PR/READY2MERGE

#2899 Release of 0.6.0
  debian/changelog
  meson.build
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#2901 [Tensor] Fix improper vector initialization in Tensor::split function
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/half_tensor.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
  test/unittest/unittest_nntrainer_tensor_fp16.cpp
Labels: bug, PR/READY2MERGE
