Repository nnstreamer/nntrainer, pull requests merged in 2025-03, with the labels that each got.

#2861 [CharTensor] QINT8 addition feature
  nntrainer/tensor/char_tensor.cpp
  nntrainer/tensor/char_tensor.h
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: PR/READY2MERGE

#2972 [cov] fixed coverity issues
  Applications/ProductRatings/jni/main.cpp
  nntrainer/tensor/swap_device.cpp
Labels: PR/READY2MERGE

#2976 [tizen] fix svace&coverity issues in application
  Applications/LLaMA/jni/main.cpp
  Applications/ProductRatings/jni/main.cpp
  Applications/TransferLearning/CIFAR_Classification/jni/main.cpp
  Applications/TransferLearning/CIFAR_Classification/jni/main_func.cpp
  Applications/YOLOv3/jni/main.cpp
  nntrainer/dataset/dir_data_producers.cpp
  nntrainer/tensor/task_executor.cpp
Labels: Need Review

#2961 [meson] Use nproc for number of cores
  jni/meson.build
  meson.build
  test/jni/meson.build
Labels: PR/READY2MERGE

#2983 [Foramt] Update .clang-format file with valid parm & value
  .clang-format
Labels: PR/READY2MERGE

#2952 [Windows] Build applications tests and benchmarks on Windows [Include #2924 changes]
  Applications/AlexNet/jni/meson.build
  Applications/Custom/LayerClient/jni/meson.build
  Applications/Layers/jni/meson.build
  Applications/LogisticRegression/jni/main.cpp
  Applications/LogisticRegression/jni/meson.build
  Applications/MNIST/jni/main.cpp
  Applications/MNIST/jni/meson.build
  Applications/Multi_input/jni/multi_loader.cpp
  Applications/ProductRatings/jni/main.cpp
  Applications/ProductRatings/jni/meson.build
  Applications/ReinforcementLearning/DeepQ/jni/meson.build
  Applications/SimpleFC/jni/main.cpp
  Applications/YOLOv2/jni/det_dataloader.cpp
  Applications/YOLOv3/jni/det_dataloader.cpp
  Applications/meson.build
  Applications/utils/datagen/cifar/cifar_dataloader.cpp
  Applications/utils/jni/bitmap_helpers.cpp
  benchmarks/benchmark_application/benchmark_resnet.cpp
  benchmarks/benchmark_application/meson.build
  benchmarks/fake_data_gen/fake_data_gen.cpp
  meson.build
  nntrainer/app_context.cpp
  nntrainer/meson.build
  nntrainer/models/model_loader.cpp
  nntrainer/tensor/blas_avx.cpp
  subprojects/benchmark.wrap
  subprojects/googletest.wrap
  subprojects/openblas.wrap
  test/meson.build
  test/nntrainer_test_util.cpp
  test/unittest/compiler/meson.build
  test/unittest/datasets/unittest_iteration_queue.cpp
  test/unittest/integration_tests/integration_test_loss.cpp
  test/unittest/layers/meson.build
  test/unittest/memory/meson.build
  test/unittest/memory/unittest_memory_planner.cpp
  test/unittest/meson.build
  test/unittest/unittest_base_properties.cpp
  test/unittest/unittest_nntrainer_appcontext.cpp
  test/unittest/unittest_nntrainer_models.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
  windows-native.ini
Labels: BUILD/CI

#2986 [tizen] fix coverity issues
  api/ccapi/include/tensor_api.h
  nntrainer/dataset/dir_data_producers.cpp
Labels: PR/READY2MERGE

#2987 [Windows] Fix building tests
  nntrainer/tensor/cpu_backend/x86/avx2_impl.cpp
Labels: PR/READY2MERGE

#2992 [Coverity] Fix Coverity issue on test/tizen_capi
  test/tizen_capi/unittest_tizen_capi.cpp
Labels: PR/READY2MERGE

#2970 Enhance NNTrainer Android Build
  nntrainer/layers/gru.cpp
  nntrainer/tensor/char_tensor.h
  nntrainer/tensor/int4_tensor.h
  nntrainer/tensor/short_tensor.h
  nntrainer/tensor/uint_tensor.h
  tools/android_test.sh
Labels: PR/READY2MERGE

#2954 [refactoring] add withKey function to utility functions @open sesame 02/21 08:59
  Applications/LLaMA/jni/main.cpp
  Applications/MixedPrecision/jni/main.cpp
  Applications/Multi_input/jni/main.cpp
  Applications/Resnet/jni/main.cpp
  Applications/SimpleFC/jni/main.cpp
  Applications/YOLOv2/jni/main.cpp
  Applications/YOLOv3/jni/main.cpp
  benchmarks/benchmark_application/benchmark_resnet.cpp
  nntrainer/utils/util_func.h
  test/unittest/compiler/unittest_tflite_export.cpp
  test/unittest/integration_tests/integration_test_fsu.cpp
  test/unittest/integration_tests/integration_test_loss.cpp
  test/unittest/unittest_nntrainer_graph.cpp
Labels: PR/READY2MERGE

#2991 [Windows] Add Windows CI
  .github/workflows/windows.yml
  meson.build
Labels: PR/READY2MERGE

#2955 Add GraphNodeIterator::operator<= required by std::reverse_iterator
  nntrainer/graph/graph_node.h
Labels: PR/READY2MERGE

#2968 Add unit-tests for dotCL function, N=1, M=1 case
  test/unittest/unittest_blas_kernels_cl.cpp
Labels: PR/READY2MERGE

#2997 Fix Ubuntu build with OpenBLAS as subproject
  meson.build
Labels: PR/READY2MERGE

#2994 [ Bug ] restore the initailize function in layer
  api/ccapi/include/layer.h
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_node.h
Labels: PR/READY2MERGE

#2948 [Quantizer] Unsigned Integer Tensor Support
  nntrainer/tensor/cpu_backend/arm/arm_compute_backend.cpp
  nntrainer/tensor/cpu_backend/arm/arm_compute_backend.h
  nntrainer/tensor/cpu_backend/arm/neon_impl.cpp
  nntrainer/tensor/cpu_backend/arm/neon_impl.h
  nntrainer/tensor/cpu_backend/cpu_backend.h
  nntrainer/tensor/cpu_backend/fallback/fallback.cpp
  nntrainer/tensor/cpu_backend/fallback/fallback.h
  nntrainer/tensor/cpu_backend/fallback/fallback_internal.cpp
  nntrainer/tensor/cpu_backend/fallback/fallback_internal.h
  nntrainer/tensor/cpu_backend/x86/x86_compute_backend.cpp
  nntrainer/tensor/cpu_backend/x86/x86_compute_backend.h
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/quantizer.cpp
  nntrainer/tensor/quantizer.h
  test/unittest/unittest_nntrainer_quantizer.cpp
Labels: PR/READY2MERGE

#2998 [Windows] Fix nntrainer double to float init warnings
  nntrainer/layers/gru.cpp
  nntrainer/layers/grucell.cpp
  nntrainer/layers/lstmcell_core.cpp
  nntrainer/layers/multi_head_attention_layer.cpp
  nntrainer/layers/preprocess_translate_layer.cpp
  nntrainer/models/dynamic_training_optimization.cpp
  nntrainer/models/dynamic_training_optimization.h
Labels: PR/READY2MERGE

#3003 [tizen] fix coverity issues in appication
  Applications/LogisticRegression/jni/main.cpp
  Applications/YOLOv2/jni/main.cpp
Labels: Need Review

#3002 [FC] Minor fix in FC layer
  nntrainer/layers/fc_layer.cpp
Labels: PR/READY2MERGE

#3000 [gtest] Enable gtest built as subproject on linux
  meson.build
Labels: PR/READY2MERGE

#3005 [Windows] Check if directory exist prior running mkdir
  Applications/AlexNet/jni/meson.build
  Applications/Custom/LayerClient/jni/meson.build
  Applications/Layers/jni/meson.build
  Applications/LogisticRegression/jni/meson.build
  Applications/MNIST/jni/meson.build
  Applications/ProductRatings/jni/meson.build
  Applications/meson.build
  meson.build
  test/meson.build
  test/unittest/meson.build
Labels: PR/READY2MERGE

#3001 [ bugfix ] Fix is_valid algorithm
  nntrainer/tensor/cpu_backend/arm/arm_compute_backend_fp16.cpp
  nntrainer/tensor/cpu_backend/arm/neon_impl_fp16.cpp
Labels: PR/READY2MERGE

#3012 [gtest] Remove duplicated main() in integration unit test
  test/unittest/integration_tests/meson.build
Labels: PR/READY2MERGE

#3008 [hgemm] Removal of assert in get_prev_mltpl_of_2p_n
  nntrainer/tensor/cpu_backend/arm/hgemm/hgemm_util.cpp
Labels: PR/READY2MERGE

#3009 [Tizen][Covierty] Fix Coverity Issue on Tizen 10.0
  test/tizen_capi/unittest_tizen_capi.cpp
  test/tizen_capi/unittest_tizen_capi_lr_scheduler.cpp
Labels: PR/READY2MERGE

#3015 Fix the url to download the encoder from
  jni/prepare_encoder.sh
Labels: PR/READY2MERGE

#2951 [ONNX] add basic onnx interpreter @open sesame 02/17 20:00
  api/ccapi/include/model.h
  api/nntrainer-api-common.h
  meson.build
  nntrainer/compiler/meson.build
  nntrainer/compiler/onnx_interpreter.cpp
  nntrainer/compiler/onnx_interpreter.h
  nntrainer/models/model_loader.cpp
  nntrainer/models/model_loader.h
  nntrainer/models/neuralnet.cpp
Labels: PR/READY2MERGE

#2963 [Wait for #2962] Meson unittests suite
  test/ccapi/meson.build
  test/nnstreamer/meson.build
  test/tizen_capi/meson.build
  test/unittest/compiler/meson.build
  test/unittest/datasets/meson.build
  test/unittest/integration_tests/meson.build
  test/unittest/layers/meson.build
  test/unittest/memory/meson.build
  test/unittest/meson.build
  test/unittest/models/meson.build
Labels: PR/READY2MERGE

#2958 [Wait for #2951][application] add onnx example
  Applications/ONNX/jni/Android.mk
  Applications/ONNX/jni/Application.mk
  Applications/ONNX/jni/add_example.onnx
  Applications/ONNX/jni/main.cpp
  Applications/ONNX/jni/meson.build
  Applications/meson.build
  nntrainer/compiler/onnx_interpreter.h
Labels: PR/READY2MERGE

#3010 [CI] Add gitaction runner : Ubuntu 24.04
  .github/workflows/android.yml
  .github/workflows/daily_build.yml
  .github/workflows/gbs_build.yml
  .github/workflows/pdebuild.yml
  .github/workflows/ubuntu_benchmarks.yml
  .github/workflows/ubuntu_clean_meson_build.yml
  .github/workflows/windows.yml
  .github/workflows/yocto.yml
Labels: PR/READY2MERGE

#2989 [application] namespace duplication in llama application @open sesame 03/07 15:57
  Applications/LLaMA/jni/custom_multi_head_attention_layer.cpp
  Applications/LLaMA/jni/custom_multi_head_attention_layer.h
Labels: PR/READY2MERGE

#3016 [Wait for #2989][bug fix] key duplication in llama application
  Applications/LLaMA/jni/custom_multi_head_attention_layer.cpp
  Applications/LLaMA/jni/custom_multi_head_attention_layer.h
  Applications/LLaMA/jni/main.cpp
Labels: PR/READY2MERGE

#3019 [Fix] Fix tensor data type check .
  nntrainer/tensor/tensor.h
Labels: PR/READY2MERGE

#3030 [tensor] create bcq weight on read
  nntrainer/tensor/bcq_tensor.cpp
  nntrainer/tensor/bcq_tensor.h
Labels: Need Review

#3036 [BCQTensor] add argmin & bugfix in BCQTensor @open sesame 13:23
  nntrainer/tensor/bcq_tensor.cpp
  nntrainer/tensor/bcq_tensor.h
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_base.h
Labels: PR/READY2MERGE

#3039 [Tensor] UInt4QTensor with quantized 4-bit unsigned integer data type
  api/ccapi/include/tensor_dim.h
  debian/nntrainer-dev.install
  nntrainer/tensor/meson.build
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor_dim.cpp
  nntrainer/tensor/uint4_tensor.cpp
  nntrainer/tensor/uint4_tensor.h
  packaging/nntrainer.spec
Labels: PR/READY2MERGE

#3038 [Save] Update save action (from layer_node -> to layer-wise)
  nntrainer/layers/bn_layer.cpp
  nntrainer/layers/bn_layer.h
  nntrainer/layers/layer_devel.h
  nntrainer/layers/layer_node.cpp
Labels: PR/READY2MERGE

#3044 [Windows] Fix C4305 compilation warnings
  Applications/LLaMA/jni/custom_multi_head_attention_layer.cpp
  Applications/LLaMA/jni/main.cpp
  Applications/MNIST/jni/main.cpp
  test/unittest/datasets/unittest_random_data_producers.cpp
  test/unittest/memory/unittest_cache_pool.cpp
  test/unittest/unittest_nntrainer_activations.cpp
  test/unittest/unittest_nntrainer_lazy_tensor.cpp
  test/unittest/unittest_nntrainer_quantizer.cpp
  test/unittest/unittest_nntrainer_tensor.cpp
Labels: Need Review

#2975 Fix fp16 opencl build.
  nntrainer/layers/cl_layers/concat_cl.cpp
  nntrainer/layers/cl_layers/concat_cl.h
  nntrainer/layers/cl_layers/reshape_cl.cpp
  nntrainer/layers/cl_layers/reshape_cl.h
  nntrainer/layers/cl_layers/rmsnorm_layer_cl.cpp
  nntrainer/layers/cl_layers/swiglu_cl.cpp
  nntrainer/layers/cl_layers/swiglu_cl.h
  nntrainer/opencl/opencl_context_manager.cpp
  nntrainer/tensor/cl_operations/attention_kernels.h
  nntrainer/tensor/cl_operations/attention_kernels_fp16.cpp
  nntrainer/tensor/cl_operations/blas_kernels.h
  nntrainer/tensor/cl_operations/blas_kernels_fp16.cpp
Labels: PR/READY2MERGE

#3052 [ trivial ] Apply proper float comparison in arm backend
  nntrainer/tensor/cpu_backend/arm/hgemm/hgemm_noTrans.cpp
  nntrainer/tensor/cpu_backend/arm/neon_impl.cpp
  nntrainer/tensor/cpu_backend/arm/neon_impl_fp16.cpp
Labels: PR/READY2MERGE

#3046 [ bugfix ] Fix fp16 is_valid algorithm bug
  nntrainer/tensor/cpu_backend/arm/neon_impl_fp16.cpp
  nntrainer/tensor/swap_device.h
Labels: PR/READY2MERGE

#3057 [code clean] remove std::cout in cache_pool
  nntrainer/tensor/cache_pool.cpp
Labels: Need Review

#3058 [code clean] remove std::cout in tensor_pool
  nntrainer/tensor/tensor_pool.cpp
Labels: Need Review

#3025 Experimental win32 cross fixes
  Applications/AlexNet/jni/meson.build
  Applications/Custom/LayerClient/jni/meson.build
  Applications/Layers/jni/meson.build
  Applications/LogisticRegression/jni/meson.build
  Applications/MNIST/jni/meson.build
  Applications/ProductRatings/jni/meson.build
  Applications/meson.build
  meson.build
  nntrainer/meson.build
  test/meson.build
  test/unittest/memory/meson.build
  test/unittest/meson.build
Labels: PR/READY2MERGE

#3047 [ neon ] Add qmul8 implementation
  nntrainer/tensor/cpu_backend/arm/armv7_neon.h
  nntrainer/tensor/cpu_backend/arm/neon_impl.cpp
  nntrainer/tensor/cpu_backend/arm/neon_impl.h
Labels: PR/READY2MERGE

#3056 [Application] Refactoring llama application
  Applications/LLaMA/README.md
  Applications/LLaMA/jni/main.cpp
Labels: PR/READY2MERGE

#3029 [Tensor] Add absolute & tangent tensor operation
  nntrainer/tensor/float_tensor.cpp
  nntrainer/tensor/float_tensor.h
  nntrainer/tensor/half_tensor.cpp
  nntrainer/tensor/half_tensor.h
  nntrainer/tensor/tensor.cpp
  nntrainer/tensor/tensor.h
  nntrainer/tensor/tensor_base.cpp
  nntrainer/tensor/tensor_base.h
Labels: Need Review

#3060 [Android] Ruy as a prebuilt static library
  nntrainer/tensor/tensor_base.h
  test/jni/Android.mk
Labels: PR/READY2MERGE

#3061 [Windows] Fix D9024 warnings
  test/unittest/layers/meson.build
  test/unittest/memory/meson.build
Labels: PR/READY2MERGE
